// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: antd/v1/chunks.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_antd_v1_chunks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{0}
}

func (x *GetChunkRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_antd_v1_chunks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{1}
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkRequest) Reset() {
	*x = PutChunkRequest{}
	mi := &file_antd_v1_chunks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkRequest) ProtoMessage() {}

func (x *PutChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkRequest.ProtoReflect.Descriptor instead.
func (*PutChunkRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{2}
}

func (x *PutChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          *Cost                  `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkResponse) Reset() {
	*x = PutChunkResponse{}
	mi := &file_antd_v1_chunks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkResponse) ProtoMessage() {}

func (x *PutChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkResponse.ProtoReflect.Descriptor instead.
func (*PutChunkResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{3}
}

func (x *PutChunkResponse) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *PutChunkResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PrepareChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw chunk bytes — at most one ant-protocol chunk.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareChunkRequest) Reset() {
	*x = PrepareChunkRequest{}
	mi := &file_antd_v1_chunks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareChunkRequest) ProtoMessage() {}

func (x *PrepareChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareChunkRequest.ProtoReflect.Descriptor instead.
func (*PrepareChunkRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Mirrors REST `PrepareChunkResponse`. Single-chunk publishes are always
// wave-batch, so there are no merkle fields. When `already_stored = true`
// the payment fields are empty / zero and the caller can skip FinalizeChunk
// entirely.
type PrepareChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content-addressed BLAKE3 of the chunk bytes (hex with 0x prefix,
	// 32 bytes).
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// True if the chunk was already stored on the network. In that case no
	// payment or finalize call is needed; all subsequent fields are empty.
	AlreadyStored bool `protobuf:"varint,2,opt,name=already_stored,json=alreadyStored,proto3" json:"already_stored,omitempty"`
	// Opaque token to pass back to FinalizeChunk. Empty when
	// `already_stored == true`.
	UploadId string `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// Always "wave_batch" for single-chunk publishes. Empty when
	// `already_stored == true`.
	PaymentType string `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	// Per-quote payment entries for `payForQuotes()`. Empty when
	// `already_stored == true`.
	Payments []*PaymentEntry `protobuf:"bytes,5,rep,name=payments,proto3" json:"payments,omitempty"`
	// Total amount to pay (atto tokens as decimal string). Empty when
	// `already_stored == true`.
	TotalAmount string `protobuf:"bytes,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// Unified payment vault contract address (hex with 0x prefix). Empty when
	// `already_stored == true`.
	PaymentVaultAddress string `protobuf:"bytes,7,opt,name=payment_vault_address,json=paymentVaultAddress,proto3" json:"payment_vault_address,omitempty"`
	// Payment token contract address (hex with 0x prefix). Empty when
	// `already_stored == true`.
	PaymentTokenAddress string `protobuf:"bytes,8,opt,name=payment_token_address,json=paymentTokenAddress,proto3" json:"payment_token_address,omitempty"`
	// EVM RPC URL for submitting transactions. Empty when
	// `already_stored == true`.
	RpcUrl        string `protobuf:"bytes,9,opt,name=rpc_url,json=rpcUrl,proto3" json:"rpc_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareChunkResponse) Reset() {
	*x = PrepareChunkResponse{}
	mi := &file_antd_v1_chunks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareChunkResponse) ProtoMessage() {}

func (x *PrepareChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareChunkResponse.ProtoReflect.Descriptor instead.
func (*PrepareChunkResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareChunkResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PrepareChunkResponse) GetAlreadyStored() bool {
	if x != nil {
		return x.AlreadyStored
	}
	return false
}

func (x *PrepareChunkResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *PrepareChunkResponse) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *PrepareChunkResponse) GetPayments() []*PaymentEntry {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *PrepareChunkResponse) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *PrepareChunkResponse) GetPaymentVaultAddress() string {
	if x != nil {
		return x.PaymentVaultAddress
	}
	return ""
}

func (x *PrepareChunkResponse) GetPaymentTokenAddress() string {
	if x != nil {
		return x.PaymentTokenAddress
	}
	return ""
}

func (x *PrepareChunkResponse) GetRpcUrl() string {
	if x != nil {
		return x.RpcUrl
	}
	return ""
}

type FinalizeChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The upload_id returned from PrepareChunk.
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// Map of quote_hash (hex) → tx_hash (hex) from the on-chain payment.
	TxHashes      map[string]string `protobuf:"bytes,2,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeChunkRequest) Reset() {
	*x = FinalizeChunkRequest{}
	mi := &file_antd_v1_chunks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeChunkRequest) ProtoMessage() {}

func (x *FinalizeChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeChunkRequest.ProtoReflect.Descriptor instead.
func (*FinalizeChunkRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizeChunkRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *FinalizeChunkRequest) GetTxHashes() map[string]string {
	if x != nil {
		return x.TxHashes
	}
	return nil
}

type FinalizeChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network address of the stored chunk (hex with 0x prefix, 32 bytes).
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeChunkResponse) Reset() {
	*x = FinalizeChunkResponse{}
	mi := &file_antd_v1_chunks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeChunkResponse) ProtoMessage() {}

func (x *FinalizeChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeChunkResponse.ProtoReflect.Descriptor instead.
func (*FinalizeChunkResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{7}
}

func (x *FinalizeChunkResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_antd_v1_chunks_proto protoreflect.FileDescriptor

const file_antd_v1_chunks_proto_rawDesc = "" +
	"\n" +
	"\x14antd/v1/chunks.proto\x12\aantd.v1\x1a\x14antd/v1/common.proto\"+\n" +
	"\x0fGetChunkRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"&\n" +
	"\x10GetChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\x0fPutChunkRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"O\n" +
	"\x10PutChunkResponse\x12!\n" +
	"\x04cost\x18\x01 \x01(\v2\r.antd.v1.CostR\x04cost\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\")\n" +
	"\x13PrepareChunkRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xee\x02\n" +
	"\x14PrepareChunkResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12%\n" +
	"\x0ealready_stored\x18\x02 \x01(\bR\ralreadyStored\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x121\n" +
	"\bpayments\x18\x05 \x03(\v2\x15.antd.v1.PaymentEntryR\bpayments\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\tR\vtotalAmount\x122\n" +
	"\x15payment_vault_address\x18\a \x01(\tR\x13paymentVaultAddress\x122\n" +
	"\x15payment_token_address\x18\b \x01(\tR\x13paymentTokenAddress\x12\x17\n" +
	"\arpc_url\x18\t \x01(\tR\x06rpcUrl\"\xba\x01\n" +
	"\x14FinalizeChunkRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12H\n" +
	"\ttx_hashes\x18\x02 \x03(\v2+.antd.v1.FinalizeChunkRequest.TxHashesEntryR\btxHashes\x1a;\n" +
	"\rTxHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x15FinalizeChunkResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress2\xa3\x02\n" +
	"\fChunkService\x12:\n" +
	"\x03Get\x12\x18.antd.v1.GetChunkRequest\x1a\x19.antd.v1.GetChunkResponse\x12:\n" +
	"\x03Put\x12\x18.antd.v1.PutChunkRequest\x1a\x19.antd.v1.PutChunkResponse\x12K\n" +
	"\fPrepareChunk\x12\x1c.antd.v1.PrepareChunkRequest\x1a\x1d.antd.v1.PrepareChunkResponse\x12N\n" +
	"\rFinalizeChunk\x12\x1d.antd.v1.FinalizeChunkRequest\x1a\x1e.antd.v1.FinalizeChunkResponseBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_chunks_proto_rawDescOnce sync.Once
	file_antd_v1_chunks_proto_rawDescData []byte
)

func file_antd_v1_chunks_proto_rawDescGZIP() []byte {
	file_antd_v1_chunks_proto_rawDescOnce.Do(func() {
		file_antd_v1_chunks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_chunks_proto_rawDesc), len(file_antd_v1_chunks_proto_rawDesc)))
	})
	return file_antd_v1_chunks_proto_rawDescData
}

var file_antd_v1_chunks_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_antd_v1_chunks_proto_goTypes = []any{
	(*GetChunkRequest)(nil),       // 0: antd.v1.GetChunkRequest
	(*GetChunkResponse)(nil),      // 1: antd.v1.GetChunkResponse
	(*PutChunkRequest)(nil),       // 2: antd.v1.PutChunkRequest
	(*PutChunkResponse)(nil),      // 3: antd.v1.PutChunkResponse
	(*PrepareChunkRequest)(nil),   // 4: antd.v1.PrepareChunkRequest
	(*PrepareChunkResponse)(nil),  // 5: antd.v1.PrepareChunkResponse
	(*FinalizeChunkRequest)(nil),  // 6: antd.v1.FinalizeChunkRequest
	(*FinalizeChunkResponse)(nil), // 7: antd.v1.FinalizeChunkResponse
	nil,                           // 8: antd.v1.FinalizeChunkRequest.TxHashesEntry
	(*Cost)(nil),                  // 9: antd.v1.Cost
	(*PaymentEntry)(nil),          // 10: antd.v1.PaymentEntry
}
var file_antd_v1_chunks_proto_depIdxs = []int32{
	9,  // 0: antd.v1.PutChunkResponse.cost:type_name -> antd.v1.Cost
	10, // 1: antd.v1.PrepareChunkResponse.payments:type_name -> antd.v1.PaymentEntry
	8,  // 2: antd.v1.FinalizeChunkRequest.tx_hashes:type_name -> antd.v1.FinalizeChunkRequest.TxHashesEntry
	0,  // 3: antd.v1.ChunkService.Get:input_type -> antd.v1.GetChunkRequest
	2,  // 4: antd.v1.ChunkService.Put:input_type -> antd.v1.PutChunkRequest
	4,  // 5: antd.v1.ChunkService.PrepareChunk:input_type -> antd.v1.PrepareChunkRequest
	6,  // 6: antd.v1.ChunkService.FinalizeChunk:input_type -> antd.v1.FinalizeChunkRequest
	1,  // 7: antd.v1.ChunkService.Get:output_type -> antd.v1.GetChunkResponse
	3,  // 8: antd.v1.ChunkService.Put:output_type -> antd.v1.PutChunkResponse
	5,  // 9: antd.v1.ChunkService.PrepareChunk:output_type -> antd.v1.PrepareChunkResponse
	7,  // 10: antd.v1.ChunkService.FinalizeChunk:output_type -> antd.v1.FinalizeChunkResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_antd_v1_chunks_proto_init() }
func file_antd_v1_chunks_proto_init() {
	if File_antd_v1_chunks_proto != nil {
		return
	}
	file_antd_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_chunks_proto_rawDesc), len(file_antd_v1_chunks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_chunks_proto_goTypes,
		DependencyIndexes: file_antd_v1_chunks_proto_depIdxs,
		MessageInfos:      file_antd_v1_chunks_proto_msgTypes,
	}.Build()
	File_antd_v1_chunks_proto = out.File
	file_antd_v1_chunks_proto_goTypes = nil
	file_antd_v1_chunks_proto_depIdxs = nil
}
