// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: antd/v1/chunks.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkService_Get_FullMethodName           = "/antd.v1.ChunkService/Get"
	ChunkService_Put_FullMethodName           = "/antd.v1.ChunkService/Put"
	ChunkService_PrepareChunk_FullMethodName  = "/antd.v1.ChunkService/PrepareChunk"
	ChunkService_FinalizeChunk_FullMethodName = "/antd.v1.ChunkService/FinalizeChunk"
)

// ChunkServiceClient is the client API for ChunkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkServiceClient interface {
	Get(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error)
	Put(ctx context.Context, in *PutChunkRequest, opts ...grpc.CallOption) (*PutChunkResponse, error)
	// External-signer single-chunk publish. Mirrors REST
	// `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
	// below the merkle threshold, so the payment shape is always wave-batch.
	// When the chunk is already on-network, the prepare response has
	// `already_stored = true` and the caller can skip the finalize step.
	PrepareChunk(ctx context.Context, in *PrepareChunkRequest, opts ...grpc.CallOption) (*PrepareChunkResponse, error)
	FinalizeChunk(ctx context.Context, in *FinalizeChunkRequest, opts ...grpc.CallOption) (*FinalizeChunkResponse, error)
}

type chunkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkServiceClient(cc grpc.ClientConnInterface) ChunkServiceClient {
	return &chunkServiceClient{cc}
}

func (c *chunkServiceClient) Get(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) Put(ctx context.Context, in *PutChunkRequest, opts ...grpc.CallOption) (*PutChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) PrepareChunk(ctx context.Context, in *PrepareChunkRequest, opts ...grpc.CallOption) (*PrepareChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_PrepareChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) FinalizeChunk(ctx context.Context, in *FinalizeChunkRequest, opts ...grpc.CallOption) (*FinalizeChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_FinalizeChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServiceServer is the server API for ChunkService service.
// All implementations must embed UnimplementedChunkServiceServer
// for forward compatibility.
type ChunkServiceServer interface {
	Get(context.Context, *GetChunkRequest) (*GetChunkResponse, error)
	Put(context.Context, *PutChunkRequest) (*PutChunkResponse, error)
	// External-signer single-chunk publish. Mirrors REST
	// `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
	// below the merkle threshold, so the payment shape is always wave-batch.
	// When the chunk is already on-network, the prepare response has
	// `already_stored = true` and the caller can skip the finalize step.
	PrepareChunk(context.Context, *PrepareChunkRequest) (*PrepareChunkResponse, error)
	FinalizeChunk(context.Context, *FinalizeChunkRequest) (*FinalizeChunkResponse, error)
	mustEmbedUnimplementedChunkServiceServer()
}

// UnimplementedChunkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkServiceServer struct{}

func (UnimplementedChunkServiceServer) Get(context.Context, *GetChunkRequest) (*GetChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedChunkServiceServer) Put(context.Context, *PutChunkRequest) (*PutChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedChunkServiceServer) PrepareChunk(context.Context, *PrepareChunkRequest) (*PrepareChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareChunk not implemented")
}
func (UnimplementedChunkServiceServer) FinalizeChunk(context.Context, *FinalizeChunkRequest) (*FinalizeChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeChunk not implemented")
}
func (UnimplementedChunkServiceServer) mustEmbedUnimplementedChunkServiceServer() {}
func (UnimplementedChunkServiceServer) testEmbeddedByValue()                      {}

// UnsafeChunkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServiceServer will
// result in compilation errors.
type UnsafeChunkServiceServer interface {
	mustEmbedUnimplementedChunkServiceServer()
}

func RegisterChunkServiceServer(s grpc.ServiceRegistrar, srv ChunkServiceServer) {
	// If the following call panics, it indicates UnimplementedChunkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkService_ServiceDesc, srv)
}

func _ChunkService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).Get(ctx, req.(*GetChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).Put(ctx, req.(*PutChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_PrepareChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).PrepareChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_PrepareChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).PrepareChunk(ctx, req.(*PrepareChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_FinalizeChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).FinalizeChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_FinalizeChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).FinalizeChunk(ctx, req.(*FinalizeChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkService_ServiceDesc is the grpc.ServiceDesc for ChunkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antd.v1.ChunkService",
	HandlerType: (*ChunkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ChunkService_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _ChunkService_Put_Handler,
		},
		{
			MethodName: "PrepareChunk",
			Handler:    _ChunkService_PrepareChunk_Handler,
		},
		{
			MethodName: "FinalizeChunk",
			Handler:    _ChunkService_FinalizeChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "antd/v1/chunks.proto",
}
