// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: antd/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cost struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AttoTokens          string                 `protobuf:"bytes,1,opt,name=atto_tokens,json=attoTokens,proto3" json:"atto_tokens,omitempty"`                                // storage cost in atto tokens as string
	FileSize            uint64                 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                                     // original file size in bytes
	ChunkCount          uint32                 `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`                               // number of data chunks the file splits into
	EstimatedGasCostWei string                 `protobuf:"bytes,4,opt,name=estimated_gas_cost_wei,json=estimatedGasCostWei,proto3" json:"estimated_gas_cost_wei,omitempty"` // gas heuristic as string (can exceed JS safe int)
	PaymentMode         string                 `protobuf:"bytes,5,opt,name=payment_mode,json=paymentMode,proto3" json:"payment_mode,omitempty"`                             // "auto" | "merkle" | "single"
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_antd_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_antd_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Cost) GetAttoTokens() string {
	if x != nil {
		return x.AttoTokens
	}
	return ""
}

func (x *Cost) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Cost) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *Cost) GetEstimatedGasCostWei() string {
	if x != nil {
		return x.EstimatedGasCostWei
	}
	return ""
}

func (x *Cost) GetPaymentMode() string {
	if x != nil {
		return x.PaymentMode
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hex           string                 `protobuf:"bytes,1,opt,name=hex,proto3" json:"hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_antd_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_antd_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

type PublicKeyProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hex           string                 `protobuf:"bytes,1,opt,name=hex,proto3" json:"hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyProto) Reset() {
	*x = PublicKeyProto{}
	mi := &file_antd_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyProto) ProtoMessage() {}

func (x *PublicKeyProto) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyProto.ProtoReflect.Descriptor instead.
func (*PublicKeyProto) Descriptor() ([]byte, []int) {
	return file_antd_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PublicKeyProto) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

type SecretKeyProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hex           string                 `protobuf:"bytes,1,opt,name=hex,proto3" json:"hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretKeyProto) Reset() {
	*x = SecretKeyProto{}
	mi := &file_antd_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretKeyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretKeyProto) ProtoMessage() {}

func (x *SecretKeyProto) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretKeyProto.ProtoReflect.Descriptor instead.
func (*SecretKeyProto) Descriptor() ([]byte, []int) {
	return file_antd_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *SecretKeyProto) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

// External-signer per-quote payment entry. Shared by `UploadService` (file +
// data prepare, wave-batch path) and `ChunkService.PrepareChunk`.
type PaymentEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quote hash (hex with 0x prefix, 32 bytes).
	QuoteHash string `protobuf:"bytes,1,opt,name=quote_hash,json=quoteHash,proto3" json:"quote_hash,omitempty"`
	// Rewards address (hex with 0x prefix, 20 bytes).
	RewardsAddress string `protobuf:"bytes,2,opt,name=rewards_address,json=rewardsAddress,proto3" json:"rewards_address,omitempty"`
	// Amount to pay (atto tokens as decimal string).
	Amount        string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentEntry) Reset() {
	*x = PaymentEntry{}
	mi := &file_antd_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEntry) ProtoMessage() {}

func (x *PaymentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEntry.ProtoReflect.Descriptor instead.
func (*PaymentEntry) Descriptor() ([]byte, []int) {
	return file_antd_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentEntry) GetQuoteHash() string {
	if x != nil {
		return x.QuoteHash
	}
	return ""
}

func (x *PaymentEntry) GetRewardsAddress() string {
	if x != nil {
		return x.RewardsAddress
	}
	return ""
}

func (x *PaymentEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_antd_v1_common_proto protoreflect.FileDescriptor

const file_antd_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x14antd/v1/common.proto\x12\aantd.v1\"\xbd\x01\n" +
	"\x04Cost\x12\x1f\n" +
	"\vatto_tokens\x18\x01 \x01(\tR\n" +
	"attoTokens\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\rR\n" +
	"chunkCount\x123\n" +
	"\x16estimated_gas_cost_wei\x18\x04 \x01(\tR\x13estimatedGasCostWei\x12!\n" +
	"\fpayment_mode\x18\x05 \x01(\tR\vpaymentMode\"\x1b\n" +
	"\aAddress\x12\x10\n" +
	"\x03hex\x18\x01 \x01(\tR\x03hex\"\"\n" +
	"\x0ePublicKeyProto\x12\x10\n" +
	"\x03hex\x18\x01 \x01(\tR\x03hex\"\"\n" +
	"\x0eSecretKeyProto\x12\x10\n" +
	"\x03hex\x18\x01 \x01(\tR\x03hex\"n\n" +
	"\fPaymentEntry\x12\x1d\n" +
	"\n" +
	"quote_hash\x18\x01 \x01(\tR\tquoteHash\x12'\n" +
	"\x0frewards_address\x18\x02 \x01(\tR\x0erewardsAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amountBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_common_proto_rawDescOnce sync.Once
	file_antd_v1_common_proto_rawDescData []byte
)

func file_antd_v1_common_proto_rawDescGZIP() []byte {
	file_antd_v1_common_proto_rawDescOnce.Do(func() {
		file_antd_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_common_proto_rawDesc), len(file_antd_v1_common_proto_rawDesc)))
	})
	return file_antd_v1_common_proto_rawDescData
}

var file_antd_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_antd_v1_common_proto_goTypes = []any{
	(*Cost)(nil),           // 0: antd.v1.Cost
	(*Address)(nil),        // 1: antd.v1.Address
	(*PublicKeyProto)(nil), // 2: antd.v1.PublicKeyProto
	(*SecretKeyProto)(nil), // 3: antd.v1.SecretKeyProto
	(*PaymentEntry)(nil),   // 4: antd.v1.PaymentEntry
}
var file_antd_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_antd_v1_common_proto_init() }
func file_antd_v1_common_proto_init() {
	if File_antd_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_common_proto_rawDesc), len(file_antd_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_antd_v1_common_proto_goTypes,
		DependencyIndexes: file_antd_v1_common_proto_depIdxs,
		MessageInfos:      file_antd_v1_common_proto_msgTypes,
	}.Build()
	File_antd_v1_common_proto = out.File
	file_antd_v1_common_proto_goTypes = nil
	file_antd_v1_common_proto_depIdxs = nil
}
