// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: antd/v1/data.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_Put_FullMethodName          = "/antd.v1.DataService/Put"
	DataService_PutPublic_FullMethodName    = "/antd.v1.DataService/PutPublic"
	DataService_Get_FullMethodName          = "/antd.v1.DataService/Get"
	DataService_GetPublic_FullMethodName    = "/antd.v1.DataService/GetPublic"
	DataService_Stream_FullMethodName       = "/antd.v1.DataService/Stream"
	DataService_StreamPublic_FullMethodName = "/antd.v1.DataService/StreamPublic"
	DataService_Cost_FullMethodName         = "/antd.v1.DataService/Cost"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	// Private = unqualified verb (the DataMap is returned to the caller; it is
	// NOT stored on the network). Public = `_public` suffix (the DataMap is
	// additionally stored on-network and the call returns the resulting address).
	Put(ctx context.Context, in *PutDataRequest, opts ...grpc.CallOption) (*PutDataResponse, error)
	PutPublic(ctx context.Context, in *PutPublicDataRequest, opts ...grpc.CallOption) (*PutPublicDataResponse, error)
	Get(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	GetPublic(ctx context.Context, in *GetPublicDataRequest, opts ...grpc.CallOption) (*GetPublicDataResponse, error)
	// Streaming downloads — constant memory, one decrypt batch at a time.
	// Private streams from a caller-held DataMap; public resolves the address
	// to a DataMap first (Stream is the primitive, StreamPublic wraps it).
	Stream(ctx context.Context, in *StreamDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	StreamPublic(ctx context.Context, in *StreamPublicDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	Cost(ctx context.Context, in *DataCostRequest, opts ...grpc.CallOption) (*Cost, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) Put(ctx context.Context, in *PutDataRequest, opts ...grpc.CallOption) (*PutDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutDataResponse)
	err := c.cc.Invoke(ctx, DataService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) PutPublic(ctx context.Context, in *PutPublicDataRequest, opts ...grpc.CallOption) (*PutPublicDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPublicDataResponse)
	err := c.cc.Invoke(ctx, DataService_PutPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) Get(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, DataService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetPublic(ctx context.Context, in *GetPublicDataRequest, opts ...grpc.CallOption) (*GetPublicDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicDataResponse)
	err := c.cc.Invoke(ctx, DataService_GetPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) Stream(ctx context.Context, in *StreamDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDataRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamClient = grpc.ServerStreamingClient[DataChunk]

func (c *dataServiceClient) StreamPublic(ctx context.Context, in *StreamPublicDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[1], DataService_StreamPublic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPublicDataRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamPublicClient = grpc.ServerStreamingClient[DataChunk]

func (c *dataServiceClient) Cost(ctx context.Context, in *DataCostRequest, opts ...grpc.CallOption) (*Cost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cost)
	err := c.cc.Invoke(ctx, DataService_Cost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	// Private = unqualified verb (the DataMap is returned to the caller; it is
	// NOT stored on the network). Public = `_public` suffix (the DataMap is
	// additionally stored on-network and the call returns the resulting address).
	Put(context.Context, *PutDataRequest) (*PutDataResponse, error)
	PutPublic(context.Context, *PutPublicDataRequest) (*PutPublicDataResponse, error)
	Get(context.Context, *GetDataRequest) (*GetDataResponse, error)
	GetPublic(context.Context, *GetPublicDataRequest) (*GetPublicDataResponse, error)
	// Streaming downloads — constant memory, one decrypt batch at a time.
	// Private streams from a caller-held DataMap; public resolves the address
	// to a DataMap first (Stream is the primitive, StreamPublic wraps it).
	Stream(*StreamDataRequest, grpc.ServerStreamingServer[DataChunk]) error
	StreamPublic(*StreamPublicDataRequest, grpc.ServerStreamingServer[DataChunk]) error
	Cost(context.Context, *DataCostRequest) (*Cost, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) Put(context.Context, *PutDataRequest) (*PutDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedDataServiceServer) PutPublic(context.Context, *PutPublicDataRequest) (*PutPublicDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutPublic not implemented")
}
func (UnimplementedDataServiceServer) Get(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDataServiceServer) GetPublic(context.Context, *GetPublicDataRequest) (*GetPublicDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublic not implemented")
}
func (UnimplementedDataServiceServer) Stream(*StreamDataRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedDataServiceServer) StreamPublic(*StreamPublicDataRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamPublic not implemented")
}
func (UnimplementedDataServiceServer) Cost(context.Context, *DataCostRequest) (*Cost, error) {
	return nil, status.Error(codes.Unimplemented, "method Cost not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Put(ctx, req.(*PutDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_PutPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPublicDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).PutPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_PutPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).PutPublic(ctx, req.(*PutPublicDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Get(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetPublic(ctx, req.(*GetPublicDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).Stream(m, &grpc.GenericServerStream[StreamDataRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamServer = grpc.ServerStreamingServer[DataChunk]

func _DataService_StreamPublic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPublicDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).StreamPublic(m, &grpc.GenericServerStream[StreamPublicDataRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamPublicServer = grpc.ServerStreamingServer[DataChunk]

func _DataService_Cost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Cost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_Cost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Cost(ctx, req.(*DataCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antd.v1.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _DataService_Put_Handler,
		},
		{
			MethodName: "PutPublic",
			Handler:    _DataService_PutPublic_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DataService_Get_Handler,
		},
		{
			MethodName: "GetPublic",
			Handler:    _DataService_GetPublic_Handler,
		},
		{
			MethodName: "Cost",
			Handler:    _DataService_Cost_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _DataService_Stream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPublic",
			Handler:       _DataService_StreamPublic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "antd/v1/data.proto",
}
