// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: antd/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_antd_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_events_proto_rawDescGZIP(), []int{0}
}

type ClientEventProto struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Kind               string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	RecordsPaid        uint64                 `protobuf:"varint,2,opt,name=records_paid,json=recordsPaid,proto3" json:"records_paid,omitempty"`
	RecordsAlreadyPaid uint64                 `protobuf:"varint,3,opt,name=records_already_paid,json=recordsAlreadyPaid,proto3" json:"records_already_paid,omitempty"`
	TokensSpent        string                 `protobuf:"bytes,4,opt,name=tokens_spent,json=tokensSpent,proto3" json:"tokens_spent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientEventProto) Reset() {
	*x = ClientEventProto{}
	mi := &file_antd_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEventProto) ProtoMessage() {}

func (x *ClientEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEventProto.ProtoReflect.Descriptor instead.
func (*ClientEventProto) Descriptor() ([]byte, []int) {
	return file_antd_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ClientEventProto) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ClientEventProto) GetRecordsPaid() uint64 {
	if x != nil {
		return x.RecordsPaid
	}
	return 0
}

func (x *ClientEventProto) GetRecordsAlreadyPaid() uint64 {
	if x != nil {
		return x.RecordsAlreadyPaid
	}
	return 0
}

func (x *ClientEventProto) GetTokensSpent() string {
	if x != nil {
		return x.TokensSpent
	}
	return ""
}

var File_antd_v1_events_proto protoreflect.FileDescriptor

const file_antd_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x14antd/v1/events.proto\x12\aantd.v1\"\x12\n" +
	"\x10SubscribeRequest\"\x9e\x01\n" +
	"\x10ClientEventProto\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12!\n" +
	"\frecords_paid\x18\x02 \x01(\x04R\vrecordsPaid\x120\n" +
	"\x14records_already_paid\x18\x03 \x01(\x04R\x12recordsAlreadyPaid\x12!\n" +
	"\ftokens_spent\x18\x04 \x01(\tR\vtokensSpent2S\n" +
	"\fEventService\x12C\n" +
	"\tSubscribe\x12\x19.antd.v1.SubscribeRequest\x1a\x19.antd.v1.ClientEventProto0\x01BDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_events_proto_rawDescOnce sync.Once
	file_antd_v1_events_proto_rawDescData []byte
)

func file_antd_v1_events_proto_rawDescGZIP() []byte {
	file_antd_v1_events_proto_rawDescOnce.Do(func() {
		file_antd_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_events_proto_rawDesc), len(file_antd_v1_events_proto_rawDesc)))
	})
	return file_antd_v1_events_proto_rawDescData
}

var file_antd_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_antd_v1_events_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: antd.v1.SubscribeRequest
	(*ClientEventProto)(nil), // 1: antd.v1.ClientEventProto
}
var file_antd_v1_events_proto_depIdxs = []int32{
	0, // 0: antd.v1.EventService.Subscribe:input_type -> antd.v1.SubscribeRequest
	1, // 1: antd.v1.EventService.Subscribe:output_type -> antd.v1.ClientEventProto
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_antd_v1_events_proto_init() }
func file_antd_v1_events_proto_init() {
	if File_antd_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_events_proto_rawDesc), len(file_antd_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_events_proto_goTypes,
		DependencyIndexes: file_antd_v1_events_proto_depIdxs,
		MessageInfos:      file_antd_v1_events_proto_msgTypes,
	}.Build()
	File_antd_v1_events_proto = out.File
	file_antd_v1_events_proto_goTypes = nil
	file_antd_v1_events_proto_depIdxs = nil
}
