// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: antd/v1/health.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_antd_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_health_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                        // "ok"
	Network             string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`                                                      // "default", "local", "alpha"
	Version             string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                      // antd crate version (e.g. "0.4.0")
	EvmNetwork          string                 `protobuf:"bytes,4,opt,name=evm_network,json=evmNetwork,proto3" json:"evm_network,omitempty"`                              // EVM preset: "arbitrum-one", "arbitrum-sepolia", "local", "custom"
	UptimeSeconds       uint64                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                    // seconds since process start
	BuildCommit         string                 `protobuf:"bytes,6,opt,name=build_commit,json=buildCommit,proto3" json:"build_commit,omitempty"`                           // short git SHA, or "" if built outside a git checkout
	PaymentTokenAddress string                 `protobuf:"bytes,7,opt,name=payment_token_address,json=paymentTokenAddress,proto3" json:"payment_token_address,omitempty"` // token contract, or "" if unconfigured
	PaymentVaultAddress string                 `protobuf:"bytes,8,opt,name=payment_vault_address,json=paymentVaultAddress,proto3" json:"payment_vault_address,omitempty"` // payment vault contract, or "" if unconfigured
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_antd_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetEvmNetwork() string {
	if x != nil {
		return x.EvmNetwork
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetBuildCommit() string {
	if x != nil {
		return x.BuildCommit
	}
	return ""
}

func (x *HealthCheckResponse) GetPaymentTokenAddress() string {
	if x != nil {
		return x.PaymentTokenAddress
	}
	return ""
}

func (x *HealthCheckResponse) GetPaymentVaultAddress() string {
	if x != nil {
		return x.PaymentVaultAddress
	}
	return ""
}

var File_antd_v1_health_proto protoreflect.FileDescriptor

const file_antd_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x14antd/v1/health.proto\x12\aantd.v1\"\x14\n" +
	"\x12HealthCheckRequest\"\xb4\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vevm_network\x18\x04 \x01(\tR\n" +
	"evmNetwork\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12!\n" +
	"\fbuild_commit\x18\x06 \x01(\tR\vbuildCommit\x122\n" +
	"\x15payment_token_address\x18\a \x01(\tR\x13paymentTokenAddress\x122\n" +
	"\x15payment_vault_address\x18\b \x01(\tR\x13paymentVaultAddress2S\n" +
	"\rHealthService\x12B\n" +
	"\x05Check\x12\x1b.antd.v1.HealthCheckRequest\x1a\x1c.antd.v1.HealthCheckResponseBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_health_proto_rawDescOnce sync.Once
	file_antd_v1_health_proto_rawDescData []byte
)

func file_antd_v1_health_proto_rawDescGZIP() []byte {
	file_antd_v1_health_proto_rawDescOnce.Do(func() {
		file_antd_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_health_proto_rawDesc), len(file_antd_v1_health_proto_rawDesc)))
	})
	return file_antd_v1_health_proto_rawDescData
}

var file_antd_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_antd_v1_health_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: antd.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: antd.v1.HealthCheckResponse
}
var file_antd_v1_health_proto_depIdxs = []int32{
	0, // 0: antd.v1.HealthService.Check:input_type -> antd.v1.HealthCheckRequest
	1, // 1: antd.v1.HealthService.Check:output_type -> antd.v1.HealthCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_antd_v1_health_proto_init() }
func file_antd_v1_health_proto_init() {
	if File_antd_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_health_proto_rawDesc), len(file_antd_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_health_proto_goTypes,
		DependencyIndexes: file_antd_v1_health_proto_depIdxs,
		MessageInfos:      file_antd_v1_health_proto_msgTypes,
	}.Build()
	File_antd_v1_health_proto = out.File
	file_antd_v1_health_proto_goTypes = nil
	file_antd_v1_health_proto_depIdxs = nil
}
