// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: antd/v1/wallet.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletAddressRequest) Reset() {
	*x = GetWalletAddressRequest{}
	mi := &file_antd_v1_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletAddressRequest) ProtoMessage() {}

func (x *GetWalletAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletAddressRequest.ProtoReflect.Descriptor instead.
func (*GetWalletAddressRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_wallet_proto_rawDescGZIP(), []int{0}
}

type GetWalletAddressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wallet address, hex with 0x prefix (20 bytes / 42 chars).
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletAddressResponse) Reset() {
	*x = GetWalletAddressResponse{}
	mi := &file_antd_v1_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletAddressResponse) ProtoMessage() {}

func (x *GetWalletAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletAddressResponse.ProtoReflect.Descriptor instead.
func (*GetWalletAddressResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetWalletBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceRequest) Reset() {
	*x = GetWalletBalanceRequest{}
	mi := &file_antd_v1_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceRequest) ProtoMessage() {}

func (x *GetWalletBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_wallet_proto_rawDescGZIP(), []int{2}
}

type GetWalletBalanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token balance, atto tokens as decimal string.
	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	// Gas (native EVM token) balance, atto tokens as decimal string.
	GasBalance    string `protobuf:"bytes,2,opt,name=gas_balance,json=gasBalance,proto3" json:"gas_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceResponse) Reset() {
	*x = GetWalletBalanceResponse{}
	mi := &file_antd_v1_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceResponse) ProtoMessage() {}

func (x *GetWalletBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetWalletBalanceResponse) GetGasBalance() string {
	if x != nil {
		return x.GasBalance
	}
	return ""
}

type WalletApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletApproveRequest) Reset() {
	*x = WalletApproveRequest{}
	mi := &file_antd_v1_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletApproveRequest) ProtoMessage() {}

func (x *WalletApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletApproveRequest.ProtoReflect.Descriptor instead.
func (*WalletApproveRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_wallet_proto_rawDescGZIP(), []int{4}
}

type WalletApproveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the approve transaction succeeded.
	Approved      bool `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletApproveResponse) Reset() {
	*x = WalletApproveResponse{}
	mi := &file_antd_v1_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletApproveResponse) ProtoMessage() {}

func (x *WalletApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletApproveResponse.ProtoReflect.Descriptor instead.
func (*WalletApproveResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *WalletApproveResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

var File_antd_v1_wallet_proto protoreflect.FileDescriptor

const file_antd_v1_wallet_proto_rawDesc = "" +
	"\n" +
	"\x14antd/v1/wallet.proto\x12\aantd.v1\"\x19\n" +
	"\x17GetWalletAddressRequest\"4\n" +
	"\x18GetWalletAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x19\n" +
	"\x17GetWalletBalanceRequest\"U\n" +
	"\x18GetWalletBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\x12\x1f\n" +
	"\vgas_balance\x18\x02 \x01(\tR\n" +
	"gasBalance\"\x16\n" +
	"\x14WalletApproveRequest\"3\n" +
	"\x15WalletApproveResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved2\xff\x01\n" +
	"\rWalletService\x12Q\n" +
	"\n" +
	"GetAddress\x12 .antd.v1.GetWalletAddressRequest\x1a!.antd.v1.GetWalletAddressResponse\x12Q\n" +
	"\n" +
	"GetBalance\x12 .antd.v1.GetWalletBalanceRequest\x1a!.antd.v1.GetWalletBalanceResponse\x12H\n" +
	"\aApprove\x12\x1d.antd.v1.WalletApproveRequest\x1a\x1e.antd.v1.WalletApproveResponseBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_wallet_proto_rawDescOnce sync.Once
	file_antd_v1_wallet_proto_rawDescData []byte
)

func file_antd_v1_wallet_proto_rawDescGZIP() []byte {
	file_antd_v1_wallet_proto_rawDescOnce.Do(func() {
		file_antd_v1_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_wallet_proto_rawDesc), len(file_antd_v1_wallet_proto_rawDesc)))
	})
	return file_antd_v1_wallet_proto_rawDescData
}

var file_antd_v1_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_antd_v1_wallet_proto_goTypes = []any{
	(*GetWalletAddressRequest)(nil),  // 0: antd.v1.GetWalletAddressRequest
	(*GetWalletAddressResponse)(nil), // 1: antd.v1.GetWalletAddressResponse
	(*GetWalletBalanceRequest)(nil),  // 2: antd.v1.GetWalletBalanceRequest
	(*GetWalletBalanceResponse)(nil), // 3: antd.v1.GetWalletBalanceResponse
	(*WalletApproveRequest)(nil),     // 4: antd.v1.WalletApproveRequest
	(*WalletApproveResponse)(nil),    // 5: antd.v1.WalletApproveResponse
}
var file_antd_v1_wallet_proto_depIdxs = []int32{
	0, // 0: antd.v1.WalletService.GetAddress:input_type -> antd.v1.GetWalletAddressRequest
	2, // 1: antd.v1.WalletService.GetBalance:input_type -> antd.v1.GetWalletBalanceRequest
	4, // 2: antd.v1.WalletService.Approve:input_type -> antd.v1.WalletApproveRequest
	1, // 3: antd.v1.WalletService.GetAddress:output_type -> antd.v1.GetWalletAddressResponse
	3, // 4: antd.v1.WalletService.GetBalance:output_type -> antd.v1.GetWalletBalanceResponse
	5, // 5: antd.v1.WalletService.Approve:output_type -> antd.v1.WalletApproveResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_antd_v1_wallet_proto_init() }
func file_antd_v1_wallet_proto_init() {
	if File_antd_v1_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_wallet_proto_rawDesc), len(file_antd_v1_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_wallet_proto_goTypes,
		DependencyIndexes: file_antd_v1_wallet_proto_depIdxs,
		MessageInfos:      file_antd_v1_wallet_proto_msgTypes,
	}.Build()
	File_antd_v1_wallet_proto = out.File
	file_antd_v1_wallet_proto_goTypes = nil
	file_antd_v1_wallet_proto_depIdxs = nil
}
