// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: antd/v1/wallet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_GetAddress_FullMethodName = "/antd.v1.WalletService/GetAddress"
	WalletService_GetBalance_FullMethodName = "/antd.v1.WalletService/GetBalance"
	WalletService_Approve_FullMethodName    = "/antd.v1.WalletService/Approve"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.
//
// All three RPCs require the daemon to have been started with a configured
// wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
// daemon returns `Status::failed_precondition` with the same "wallet not
// configured" message the REST handlers return as 503.
//
// External-signer flows do NOT use this service — they pay via off-daemon
// EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
// `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
// for callers that have entrusted a key to the daemon.
type WalletServiceClient interface {
	// Returns the wallet's on-chain address (hex with 0x prefix).
	GetAddress(ctx context.Context, in *GetWalletAddressRequest, opts ...grpc.CallOption) (*GetWalletAddressResponse, error)
	// Returns the wallet's token + gas balances.
	GetBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error)
	// Approves the wallet to spend tokens on the payment vault contract.
	// One-time operation; safe to call repeatedly (idempotent at the contract
	// level — a no-op once approval is in place).
	Approve(ctx context.Context, in *WalletApproveRequest, opts ...grpc.CallOption) (*WalletApproveResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetAddress(ctx context.Context, in *GetWalletAddressRequest, opts ...grpc.CallOption) (*GetWalletAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletAddressResponse)
	err := c.cc.Invoke(ctx, WalletService_GetAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletBalanceResponse)
	err := c.cc.Invoke(ctx, WalletService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Approve(ctx context.Context, in *WalletApproveRequest, opts ...grpc.CallOption) (*WalletApproveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletApproveResponse)
	err := c.cc.Invoke(ctx, WalletService_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
//
// Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.
//
// All three RPCs require the daemon to have been started with a configured
// wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
// daemon returns `Status::failed_precondition` with the same "wallet not
// configured" message the REST handlers return as 503.
//
// External-signer flows do NOT use this service — they pay via off-daemon
// EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
// `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
// for callers that have entrusted a key to the daemon.
type WalletServiceServer interface {
	// Returns the wallet's on-chain address (hex with 0x prefix).
	GetAddress(context.Context, *GetWalletAddressRequest) (*GetWalletAddressResponse, error)
	// Returns the wallet's token + gas balances.
	GetBalance(context.Context, *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error)
	// Approves the wallet to spend tokens on the payment vault contract.
	// One-time operation; safe to call repeatedly (idempotent at the contract
	// level — a no-op once approval is in place).
	Approve(context.Context, *WalletApproveRequest) (*WalletApproveResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) GetAddress(context.Context, *GetWalletAddressRequest) (*GetWalletAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAddress not implemented")
}
func (UnimplementedWalletServiceServer) GetBalance(context.Context, *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedWalletServiceServer) Approve(context.Context, *WalletApproveRequest) (*WalletApproveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetAddress(ctx, req.(*GetWalletAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBalance(ctx, req.(*GetWalletBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Approve(ctx, req.(*WalletApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antd.v1.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddress",
			Handler:    _WalletService_GetAddress_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _WalletService_GetBalance_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _WalletService_Approve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "antd/v1/wallet.proto",
}
