# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2
from antd._proto.antd.v1 import data_pb2 as antd_dot_v1_dot_data__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in antd/v1/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/antd.v1.DataService/Put',
                request_serializer=antd_dot_v1_dot_data__pb2.PutDataRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_data__pb2.PutDataResponse.FromString,
                _registered_method=True)
        self.PutPublic = channel.unary_unary(
                '/antd.v1.DataService/PutPublic',
                request_serializer=antd_dot_v1_dot_data__pb2.PutPublicDataRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_data__pb2.PutPublicDataResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/antd.v1.DataService/Get',
                request_serializer=antd_dot_v1_dot_data__pb2.GetDataRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_data__pb2.GetDataResponse.FromString,
                _registered_method=True)
        self.GetPublic = channel.unary_unary(
                '/antd.v1.DataService/GetPublic',
                request_serializer=antd_dot_v1_dot_data__pb2.GetPublicDataRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_data__pb2.GetPublicDataResponse.FromString,
                _registered_method=True)
        self.Stream = channel.unary_stream(
                '/antd.v1.DataService/Stream',
                request_serializer=antd_dot_v1_dot_data__pb2.StreamDataRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_data__pb2.DataChunk.FromString,
                _registered_method=True)
        self.StreamPublic = channel.unary_stream(
                '/antd.v1.DataService/StreamPublic',
                request_serializer=antd_dot_v1_dot_data__pb2.StreamPublicDataRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_data__pb2.DataChunk.FromString,
                _registered_method=True)
        self.Cost = channel.unary_unary(
                '/antd.v1.DataService/Cost',
                request_serializer=antd_dot_v1_dot_data__pb2.DataCostRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_common__pb2.Cost.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Private = unqualified verb (the DataMap is returned to the caller; it is
        NOT stored on the network). Public = `_public` suffix (the DataMap is
        additionally stored on-network and the call returns the resulting address).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutPublic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Streaming downloads — constant memory, one decrypt batch at a time.
        Private streams from a caller-held DataMap; public resolves the address
        to a DataMap first (Stream is the primitive, StreamPublic wraps it).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPublic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=antd_dot_v1_dot_data__pb2.PutDataRequest.FromString,
                    response_serializer=antd_dot_v1_dot_data__pb2.PutDataResponse.SerializeToString,
            ),
            'PutPublic': grpc.unary_unary_rpc_method_handler(
                    servicer.PutPublic,
                    request_deserializer=antd_dot_v1_dot_data__pb2.PutPublicDataRequest.FromString,
                    response_serializer=antd_dot_v1_dot_data__pb2.PutPublicDataResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=antd_dot_v1_dot_data__pb2.GetDataRequest.FromString,
                    response_serializer=antd_dot_v1_dot_data__pb2.GetDataResponse.SerializeToString,
            ),
            'GetPublic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublic,
                    request_deserializer=antd_dot_v1_dot_data__pb2.GetPublicDataRequest.FromString,
                    response_serializer=antd_dot_v1_dot_data__pb2.GetPublicDataResponse.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=antd_dot_v1_dot_data__pb2.StreamDataRequest.FromString,
                    response_serializer=antd_dot_v1_dot_data__pb2.DataChunk.SerializeToString,
            ),
            'StreamPublic': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPublic,
                    request_deserializer=antd_dot_v1_dot_data__pb2.StreamPublicDataRequest.FromString,
                    response_serializer=antd_dot_v1_dot_data__pb2.DataChunk.SerializeToString,
            ),
            'Cost': grpc.unary_unary_rpc_method_handler(
                    servicer.Cost,
                    request_deserializer=antd_dot_v1_dot_data__pb2.DataCostRequest.FromString,
                    response_serializer=antd_dot_v1_dot_common__pb2.Cost.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antd.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antd.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.DataService/Put',
            antd_dot_v1_dot_data__pb2.PutDataRequest.SerializeToString,
            antd_dot_v1_dot_data__pb2.PutDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutPublic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.DataService/PutPublic',
            antd_dot_v1_dot_data__pb2.PutPublicDataRequest.SerializeToString,
            antd_dot_v1_dot_data__pb2.PutPublicDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.DataService/Get',
            antd_dot_v1_dot_data__pb2.GetDataRequest.SerializeToString,
            antd_dot_v1_dot_data__pb2.GetDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.DataService/GetPublic',
            antd_dot_v1_dot_data__pb2.GetPublicDataRequest.SerializeToString,
            antd_dot_v1_dot_data__pb2.GetPublicDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/antd.v1.DataService/Stream',
            antd_dot_v1_dot_data__pb2.StreamDataRequest.SerializeToString,
            antd_dot_v1_dot_data__pb2.DataChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPublic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/antd.v1.DataService/StreamPublic',
            antd_dot_v1_dot_data__pb2.StreamPublicDataRequest.SerializeToString,
            antd_dot_v1_dot_data__pb2.DataChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.DataService/Cost',
            antd_dot_v1_dot_data__pb2.DataCostRequest.SerializeToString,
            antd_dot_v1_dot_common__pb2.Cost.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
