# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2
from antd._proto.antd.v1 import files_pb2 as antd_dot_v1_dot_files__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in antd/v1/files_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/antd.v1.FileService/Put',
                request_serializer=antd_dot_v1_dot_files__pb2.PutFileRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_files__pb2.PutFileResponse.FromString,
                _registered_method=True)
        self.PutPublic = channel.unary_unary(
                '/antd.v1.FileService/PutPublic',
                request_serializer=antd_dot_v1_dot_files__pb2.PutFileRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_files__pb2.PutFilePublicResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/antd.v1.FileService/Get',
                request_serializer=antd_dot_v1_dot_files__pb2.GetFileRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_files__pb2.GetFileResponse.FromString,
                _registered_method=True)
        self.GetPublic = channel.unary_unary(
                '/antd.v1.FileService/GetPublic',
                request_serializer=antd_dot_v1_dot_files__pb2.GetFilePublicRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_files__pb2.GetFileResponse.FromString,
                _registered_method=True)
        self.Cost = channel.unary_unary(
                '/antd.v1.FileService/Cost',
                request_serializer=antd_dot_v1_dot_files__pb2.FileCostRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_common__pb2.Cost.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Private = unqualified verb (the DataMap is returned to the caller; it is
        NOT stored on the network). Public = `_public` suffix (the DataMap is
        additionally stored on-network and the call returns the resulting address).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutPublic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=antd_dot_v1_dot_files__pb2.PutFileRequest.FromString,
                    response_serializer=antd_dot_v1_dot_files__pb2.PutFileResponse.SerializeToString,
            ),
            'PutPublic': grpc.unary_unary_rpc_method_handler(
                    servicer.PutPublic,
                    request_deserializer=antd_dot_v1_dot_files__pb2.PutFileRequest.FromString,
                    response_serializer=antd_dot_v1_dot_files__pb2.PutFilePublicResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=antd_dot_v1_dot_files__pb2.GetFileRequest.FromString,
                    response_serializer=antd_dot_v1_dot_files__pb2.GetFileResponse.SerializeToString,
            ),
            'GetPublic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublic,
                    request_deserializer=antd_dot_v1_dot_files__pb2.GetFilePublicRequest.FromString,
                    response_serializer=antd_dot_v1_dot_files__pb2.GetFileResponse.SerializeToString,
            ),
            'Cost': grpc.unary_unary_rpc_method_handler(
                    servicer.Cost,
                    request_deserializer=antd_dot_v1_dot_files__pb2.FileCostRequest.FromString,
                    response_serializer=antd_dot_v1_dot_common__pb2.Cost.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antd.v1.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antd.v1.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.FileService/Put',
            antd_dot_v1_dot_files__pb2.PutFileRequest.SerializeToString,
            antd_dot_v1_dot_files__pb2.PutFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutPublic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.FileService/PutPublic',
            antd_dot_v1_dot_files__pb2.PutFileRequest.SerializeToString,
            antd_dot_v1_dot_files__pb2.PutFilePublicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.FileService/Get',
            antd_dot_v1_dot_files__pb2.GetFileRequest.SerializeToString,
            antd_dot_v1_dot_files__pb2.GetFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.FileService/GetPublic',
            antd_dot_v1_dot_files__pb2.GetFilePublicRequest.SerializeToString,
            antd_dot_v1_dot_files__pb2.GetFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.FileService/Cost',
            antd_dot_v1_dot_files__pb2.FileCostRequest.SerializeToString,
            antd_dot_v1_dot_common__pb2.Cost.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
