# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from antd._proto.antd.v1 import upload_pb2 as antd_dot_v1_dot_upload__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in antd/v1/upload_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UploadServiceStub(object):
    """External-signer flow for files + in-memory data. Mirrors the REST
    `/v1/upload/prepare`, `/v1/data/prepare`, `/v1/upload/finalize` surface 1:1.

    Two-phase: caller submits a prepare request, daemon collects quotes from the
    network and stashes server-side state keyed by `upload_id`. Caller then
    signs + submits the EVM payment off-daemon, then calls FinalizeUpload with
    the resulting transaction artefacts.

    Wave-batch (files with < 64 chunks): per-quote payments via `payForQuotes()`.
    Merkle (files with >= 64 chunks): pool commitments via `payForMerkleTree2()`.

    File and data prepares are intentionally separate RPCs (their request shapes
    differ — filesystem path vs raw bytes), but they share one finalize RPC
    because the server-side stored state is the same shape either way.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareFileUpload = channel.unary_unary(
                '/antd.v1.UploadService/PrepareFileUpload',
                request_serializer=antd_dot_v1_dot_upload__pb2.PrepareFileUploadRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_upload__pb2.PrepareUploadResponse.FromString,
                _registered_method=True)
        self.PrepareDataUpload = channel.unary_unary(
                '/antd.v1.UploadService/PrepareDataUpload',
                request_serializer=antd_dot_v1_dot_upload__pb2.PrepareDataUploadRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_upload__pb2.PrepareUploadResponse.FromString,
                _registered_method=True)
        self.FinalizeUpload = channel.unary_unary(
                '/antd.v1.UploadService/FinalizeUpload',
                request_serializer=antd_dot_v1_dot_upload__pb2.FinalizeUploadRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_upload__pb2.FinalizeUploadResponse.FromString,
                _registered_method=True)


class UploadServiceServicer(object):
    """External-signer flow for files + in-memory data. Mirrors the REST
    `/v1/upload/prepare`, `/v1/data/prepare`, `/v1/upload/finalize` surface 1:1.

    Two-phase: caller submits a prepare request, daemon collects quotes from the
    network and stashes server-side state keyed by `upload_id`. Caller then
    signs + submits the EVM payment off-daemon, then calls FinalizeUpload with
    the resulting transaction artefacts.

    Wave-batch (files with < 64 chunks): per-quote payments via `payForQuotes()`.
    Merkle (files with >= 64 chunks): pool commitments via `payForMerkleTree2()`.

    File and data prepares are intentionally separate RPCs (their request shapes
    differ — filesystem path vs raw bytes), but they share one finalize RPC
    because the server-side stored state is the same shape either way.
    """

    def PrepareFileUpload(self, request, context):
        """Phase 1: prepare a file upload for external signing. Returns payment
        details + an upload_id. For files with < 64 chunks returns
        `payment_type = "wave_batch"`; otherwise `payment_type = "merkle"`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareDataUpload(self, request, context):
        """Phase 1 (data): prepare an in-memory data upload for external signing.
        Same as PrepareFileUpload but takes raw bytes instead of a filesystem
        path. Honours visibility = "public" (requires ant-client #73, already
        merged on main since 2026-05-05).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeUpload(self, request, context):
        """Phase 2: finalize an upload after the external EVM payment has landed.
        For wave-batch uploads pass `tx_hashes`; for merkle uploads pass
        `winner_pool_hash` from the `MerklePaymentMade` event. The server-side
        stored upload state is consumed (one-shot).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareFileUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareFileUpload,
                    request_deserializer=antd_dot_v1_dot_upload__pb2.PrepareFileUploadRequest.FromString,
                    response_serializer=antd_dot_v1_dot_upload__pb2.PrepareUploadResponse.SerializeToString,
            ),
            'PrepareDataUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareDataUpload,
                    request_deserializer=antd_dot_v1_dot_upload__pb2.PrepareDataUploadRequest.FromString,
                    response_serializer=antd_dot_v1_dot_upload__pb2.PrepareUploadResponse.SerializeToString,
            ),
            'FinalizeUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeUpload,
                    request_deserializer=antd_dot_v1_dot_upload__pb2.FinalizeUploadRequest.FromString,
                    response_serializer=antd_dot_v1_dot_upload__pb2.FinalizeUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antd.v1.UploadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antd.v1.UploadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UploadService(object):
    """External-signer flow for files + in-memory data. Mirrors the REST
    `/v1/upload/prepare`, `/v1/data/prepare`, `/v1/upload/finalize` surface 1:1.

    Two-phase: caller submits a prepare request, daemon collects quotes from the
    network and stashes server-side state keyed by `upload_id`. Caller then
    signs + submits the EVM payment off-daemon, then calls FinalizeUpload with
    the resulting transaction artefacts.

    Wave-batch (files with < 64 chunks): per-quote payments via `payForQuotes()`.
    Merkle (files with >= 64 chunks): pool commitments via `payForMerkleTree2()`.

    File and data prepares are intentionally separate RPCs (their request shapes
    differ — filesystem path vs raw bytes), but they share one finalize RPC
    because the server-side stored state is the same shape either way.
    """

    @staticmethod
    def PrepareFileUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.UploadService/PrepareFileUpload',
            antd_dot_v1_dot_upload__pb2.PrepareFileUploadRequest.SerializeToString,
            antd_dot_v1_dot_upload__pb2.PrepareUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareDataUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.UploadService/PrepareDataUpload',
            antd_dot_v1_dot_upload__pb2.PrepareDataUploadRequest.SerializeToString,
            antd_dot_v1_dot_upload__pb2.PrepareUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.UploadService/FinalizeUpload',
            antd_dot_v1_dot_upload__pb2.FinalizeUploadRequest.SerializeToString,
            antd_dot_v1_dot_upload__pb2.FinalizeUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
