# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from antd._proto.antd.v1 import wallet_pb2 as antd_dot_v1_dot_wallet__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in antd/v1/wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletServiceStub(object):
    """Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.

    All three RPCs require the daemon to have been started with a configured
    wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
    daemon returns `Status::failed_precondition` with the same "wallet not
    configured" message the REST handlers return as 503.

    External-signer flows do NOT use this service — they pay via off-daemon
    EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
    `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
    for callers that have entrusted a key to the daemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAddress = channel.unary_unary(
                '/antd.v1.WalletService/GetAddress',
                request_serializer=antd_dot_v1_dot_wallet__pb2.GetWalletAddressRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_wallet__pb2.GetWalletAddressResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/antd.v1.WalletService/GetBalance',
                request_serializer=antd_dot_v1_dot_wallet__pb2.GetWalletBalanceRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_wallet__pb2.GetWalletBalanceResponse.FromString,
                _registered_method=True)
        self.Approve = channel.unary_unary(
                '/antd.v1.WalletService/Approve',
                request_serializer=antd_dot_v1_dot_wallet__pb2.WalletApproveRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_wallet__pb2.WalletApproveResponse.FromString,
                _registered_method=True)


class WalletServiceServicer(object):
    """Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.

    All three RPCs require the daemon to have been started with a configured
    wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
    daemon returns `Status::failed_precondition` with the same "wallet not
    configured" message the REST handlers return as 503.

    External-signer flows do NOT use this service — they pay via off-daemon
    EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
    `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
    for callers that have entrusted a key to the daemon.
    """

    def GetAddress(self, request, context):
        """Returns the wallet's on-chain address (hex with 0x prefix).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Returns the wallet's token + gas balances.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Approve(self, request, context):
        """Approves the wallet to spend tokens on the payment vault contract.
        One-time operation; safe to call repeatedly (idempotent at the contract
        level — a no-op once approval is in place).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddress,
                    request_deserializer=antd_dot_v1_dot_wallet__pb2.GetWalletAddressRequest.FromString,
                    response_serializer=antd_dot_v1_dot_wallet__pb2.GetWalletAddressResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=antd_dot_v1_dot_wallet__pb2.GetWalletBalanceRequest.FromString,
                    response_serializer=antd_dot_v1_dot_wallet__pb2.GetWalletBalanceResponse.SerializeToString,
            ),
            'Approve': grpc.unary_unary_rpc_method_handler(
                    servicer.Approve,
                    request_deserializer=antd_dot_v1_dot_wallet__pb2.WalletApproveRequest.FromString,
                    response_serializer=antd_dot_v1_dot_wallet__pb2.WalletApproveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antd.v1.WalletService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antd.v1.WalletService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.

    All three RPCs require the daemon to have been started with a configured
    wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
    daemon returns `Status::failed_precondition` with the same "wallet not
    configured" message the REST handlers return as 503.

    External-signer flows do NOT use this service — they pay via off-daemon
    EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
    `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
    for callers that have entrusted a key to the daemon.
    """

    @staticmethod
    def GetAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.WalletService/GetAddress',
            antd_dot_v1_dot_wallet__pb2.GetWalletAddressRequest.SerializeToString,
            antd_dot_v1_dot_wallet__pb2.GetWalletAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.WalletService/GetBalance',
            antd_dot_v1_dot_wallet__pb2.GetWalletBalanceRequest.SerializeToString,
            antd_dot_v1_dot_wallet__pb2.GetWalletBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Approve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.WalletService/Approve',
            antd_dot_v1_dot_wallet__pb2.WalletApproveRequest.SerializeToString,
            antd_dot_v1_dot_wallet__pb2.WalletApproveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
