# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antd/v1/wallet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antd/v1/wallet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61ntd/v1/wallet.proto\x12\x07\x61ntd.v1\"\x19\n\x17GetWalletAddressRequest\"+\n\x18GetWalletAddressResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x19\n\x17GetWalletBalanceRequest\"@\n\x18GetWalletBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\t\x12\x13\n\x0bgas_balance\x18\x02 \x01(\t\"\x16\n\x14WalletApproveRequest\")\n\x15WalletApproveResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x32\xff\x01\n\rWalletService\x12Q\n\nGetAddress\x12 .antd.v1.GetWalletAddressRequest\x1a!.antd.v1.GetWalletAddressResponse\x12Q\n\nGetBalance\x12 .antd.v1.GetWalletBalanceRequest\x1a!.antd.v1.GetWalletBalanceResponse\x12H\n\x07\x41pprove\x12\x1d.antd.v1.WalletApproveRequest\x1a\x1e.antd.v1.WalletApproveResponseBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\x07\x41ntd.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antd._proto.antd.v1.wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\252\002\007Antd.V1'
  _globals['_GETWALLETADDRESSREQUEST']._serialized_start=33
  _globals['_GETWALLETADDRESSREQUEST']._serialized_end=58
  _globals['_GETWALLETADDRESSRESPONSE']._serialized_start=60
  _globals['_GETWALLETADDRESSRESPONSE']._serialized_end=103
  _globals['_GETWALLETBALANCEREQUEST']._serialized_start=105
  _globals['_GETWALLETBALANCEREQUEST']._serialized_end=130
  _globals['_GETWALLETBALANCERESPONSE']._serialized_start=132
  _globals['_GETWALLETBALANCERESPONSE']._serialized_end=196
  _globals['_WALLETAPPROVEREQUEST']._serialized_start=198
  _globals['_WALLETAPPROVEREQUEST']._serialized_end=220
  _globals['_WALLETAPPROVERESPONSE']._serialized_start=222
  _globals['_WALLETAPPROVERESPONSE']._serialized_end=263
  _globals['_WALLETSERVICE']._serialized_start=266
  _globals['_WALLETSERVICE']._serialized_end=521
# @@protoc_insertion_point(module_scope)
