// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: antd/v1/chunks.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - antd.v1.ChunkService

/// Namespace containing generated types for the "antd.v1.ChunkService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Antd_V1_ChunkService {
    /// Service descriptor for the "antd.v1.ChunkService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.ChunkService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Get" metadata.
        public enum Get {
            /// Request type for "Get".
            public typealias Input = Antd_V1_GetChunkRequest
            /// Response type for "Get".
            public typealias Output = Antd_V1_GetChunkResponse
            /// Descriptor for "Get".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.ChunkService"),
                method: "Get"
            )
        }
        /// Namespace for "Put" metadata.
        public enum Put {
            /// Request type for "Put".
            public typealias Input = Antd_V1_PutChunkRequest
            /// Response type for "Put".
            public typealias Output = Antd_V1_PutChunkResponse
            /// Descriptor for "Put".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.ChunkService"),
                method: "Put"
            )
        }
        /// Namespace for "PrepareChunk" metadata.
        public enum PrepareChunk {
            /// Request type for "PrepareChunk".
            public typealias Input = Antd_V1_PrepareChunkRequest
            /// Response type for "PrepareChunk".
            public typealias Output = Antd_V1_PrepareChunkResponse
            /// Descriptor for "PrepareChunk".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.ChunkService"),
                method: "PrepareChunk"
            )
        }
        /// Namespace for "FinalizeChunk" metadata.
        public enum FinalizeChunk {
            /// Request type for "FinalizeChunk".
            public typealias Input = Antd_V1_FinalizeChunkRequest
            /// Response type for "FinalizeChunk".
            public typealias Output = Antd_V1_FinalizeChunkResponse
            /// Descriptor for "FinalizeChunk".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.ChunkService"),
                method: "FinalizeChunk"
            )
        }
        /// Descriptors for all methods in the "antd.v1.ChunkService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Get.descriptor,
            Put.descriptor,
            PrepareChunk.descriptor,
            FinalizeChunk.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "antd.v1.ChunkService" service.
    public static let antd_v1_ChunkService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.ChunkService")
}

// MARK: antd.v1.ChunkService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_ChunkService {
    /// Streaming variant of the service protocol for the "antd.v1.ChunkService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_GetChunkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_GetChunkResponse` messages.
        func get(
            request: GRPCCore.StreamingServerRequest<Antd_V1_GetChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_GetChunkResponse>

        /// Handle the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_PutChunkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_PutChunkResponse` messages.
        func put(
            request: GRPCCore.StreamingServerRequest<Antd_V1_PutChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_PutChunkResponse>

        /// Handle the "PrepareChunk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > External-signer single-chunk publish. Mirrors REST
        /// > `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
        /// > below the merkle threshold, so the payment shape is always wave-batch.
        /// > When the chunk is already on-network, the prepare response has
        /// > `already_stored = true` and the caller can skip the finalize step.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_PrepareChunkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_PrepareChunkResponse` messages.
        func prepareChunk(
            request: GRPCCore.StreamingServerRequest<Antd_V1_PrepareChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_PrepareChunkResponse>

        /// Handle the "FinalizeChunk" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_FinalizeChunkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_FinalizeChunkResponse` messages.
        func finalizeChunk(
            request: GRPCCore.StreamingServerRequest<Antd_V1_FinalizeChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_FinalizeChunkResponse>
    }

    /// Service protocol for the "antd.v1.ChunkService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Antd_V1_ChunkService.StreamingServiceProtocol {
        /// Handle the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetChunkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_GetChunkResponse` message.
        func get(
            request: GRPCCore.ServerRequest<Antd_V1_GetChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_GetChunkResponse>

        /// Handle the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PutChunkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_PutChunkResponse` message.
        func put(
            request: GRPCCore.ServerRequest<Antd_V1_PutChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_PutChunkResponse>

        /// Handle the "PrepareChunk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > External-signer single-chunk publish. Mirrors REST
        /// > `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
        /// > below the merkle threshold, so the payment shape is always wave-batch.
        /// > When the chunk is already on-network, the prepare response has
        /// > `already_stored = true` and the caller can skip the finalize step.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareChunkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_PrepareChunkResponse` message.
        func prepareChunk(
            request: GRPCCore.ServerRequest<Antd_V1_PrepareChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_PrepareChunkResponse>

        /// Handle the "FinalizeChunk" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_FinalizeChunkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_FinalizeChunkResponse` message.
        func finalizeChunk(
            request: GRPCCore.ServerRequest<Antd_V1_FinalizeChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_FinalizeChunkResponse>
    }

    /// Simple service protocol for the "antd.v1.ChunkService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Antd_V1_ChunkService.ServiceProtocol {
        /// Handle the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_GetChunkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_GetChunkResponse` to respond with.
        func get(
            request: Antd_V1_GetChunkRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_GetChunkResponse

        /// Handle the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_PutChunkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_PutChunkResponse` to respond with.
        func put(
            request: Antd_V1_PutChunkRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_PutChunkResponse

        /// Handle the "PrepareChunk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > External-signer single-chunk publish. Mirrors REST
        /// > `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
        /// > below the merkle threshold, so the payment shape is always wave-batch.
        /// > When the chunk is already on-network, the prepare response has
        /// > `already_stored = true` and the caller can skip the finalize step.
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_PrepareChunkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_PrepareChunkResponse` to respond with.
        func prepareChunk(
            request: Antd_V1_PrepareChunkRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_PrepareChunkResponse

        /// Handle the "FinalizeChunk" method.
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_FinalizeChunkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_FinalizeChunkResponse` to respond with.
        func finalizeChunk(
            request: Antd_V1_FinalizeChunkRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_FinalizeChunkResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_ChunkService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Antd_V1_ChunkService.Method.Get.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_GetChunkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_GetChunkResponse>(),
            handler: { request, context in
                try await self.get(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Antd_V1_ChunkService.Method.Put.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_PutChunkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_PutChunkResponse>(),
            handler: { request, context in
                try await self.put(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Antd_V1_ChunkService.Method.PrepareChunk.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_PrepareChunkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_PrepareChunkResponse>(),
            handler: { request, context in
                try await self.prepareChunk(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Antd_V1_ChunkService.Method.FinalizeChunk.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_FinalizeChunkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_FinalizeChunkResponse>(),
            handler: { request, context in
                try await self.finalizeChunk(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_ChunkService.ServiceProtocol {
    public func get(
        request: GRPCCore.StreamingServerRequest<Antd_V1_GetChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_GetChunkResponse> {
        let response = try await self.get(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func put(
        request: GRPCCore.StreamingServerRequest<Antd_V1_PutChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_PutChunkResponse> {
        let response = try await self.put(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func prepareChunk(
        request: GRPCCore.StreamingServerRequest<Antd_V1_PrepareChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_PrepareChunkResponse> {
        let response = try await self.prepareChunk(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func finalizeChunk(
        request: GRPCCore.StreamingServerRequest<Antd_V1_FinalizeChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_FinalizeChunkResponse> {
        let response = try await self.finalizeChunk(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_ChunkService.SimpleServiceProtocol {
    public func get(
        request: GRPCCore.ServerRequest<Antd_V1_GetChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_GetChunkResponse> {
        return GRPCCore.ServerResponse<Antd_V1_GetChunkResponse>(
            message: try await self.get(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func put(
        request: GRPCCore.ServerRequest<Antd_V1_PutChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_PutChunkResponse> {
        return GRPCCore.ServerResponse<Antd_V1_PutChunkResponse>(
            message: try await self.put(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func prepareChunk(
        request: GRPCCore.ServerRequest<Antd_V1_PrepareChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_PrepareChunkResponse> {
        return GRPCCore.ServerResponse<Antd_V1_PrepareChunkResponse>(
            message: try await self.prepareChunk(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func finalizeChunk(
        request: GRPCCore.ServerRequest<Antd_V1_FinalizeChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_FinalizeChunkResponse> {
        return GRPCCore.ServerResponse<Antd_V1_FinalizeChunkResponse>(
            message: try await self.finalizeChunk(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: antd.v1.ChunkService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_ChunkService {
    /// Generated client protocol for the "antd.v1.ChunkService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetChunkRequest` message.
        ///   - serializer: A serializer for `Antd_V1_GetChunkRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_GetChunkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func get<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_GetChunkRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_GetChunkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_GetChunkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetChunkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PutChunkRequest` message.
        ///   - serializer: A serializer for `Antd_V1_PutChunkRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_PutChunkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func put<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_PutChunkRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_PutChunkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_PutChunkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PutChunkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "PrepareChunk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > External-signer single-chunk publish. Mirrors REST
        /// > `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
        /// > below the merkle threshold, so the payment shape is always wave-batch.
        /// > When the chunk is already on-network, the prepare response has
        /// > `already_stored = true` and the caller can skip the finalize step.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareChunkRequest` message.
        ///   - serializer: A serializer for `Antd_V1_PrepareChunkRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_PrepareChunkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func prepareChunk<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_PrepareChunkRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_PrepareChunkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_PrepareChunkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareChunkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "FinalizeChunk" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_FinalizeChunkRequest` message.
        ///   - serializer: A serializer for `Antd_V1_FinalizeChunkRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_FinalizeChunkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func finalizeChunk<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_FinalizeChunkRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_FinalizeChunkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_FinalizeChunkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_FinalizeChunkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "antd.v1.ChunkService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetChunkRequest` message.
        ///   - serializer: A serializer for `Antd_V1_GetChunkRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_GetChunkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func get<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_GetChunkRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_GetChunkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_GetChunkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetChunkResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_ChunkService.Method.Get.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PutChunkRequest` message.
        ///   - serializer: A serializer for `Antd_V1_PutChunkRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_PutChunkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func put<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_PutChunkRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_PutChunkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_PutChunkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PutChunkResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_ChunkService.Method.Put.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "PrepareChunk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > External-signer single-chunk publish. Mirrors REST
        /// > `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
        /// > below the merkle threshold, so the payment shape is always wave-batch.
        /// > When the chunk is already on-network, the prepare response has
        /// > `already_stored = true` and the caller can skip the finalize step.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareChunkRequest` message.
        ///   - serializer: A serializer for `Antd_V1_PrepareChunkRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_PrepareChunkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func prepareChunk<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_PrepareChunkRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_PrepareChunkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_PrepareChunkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareChunkResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_ChunkService.Method.PrepareChunk.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "FinalizeChunk" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_FinalizeChunkRequest` message.
        ///   - serializer: A serializer for `Antd_V1_FinalizeChunkRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_FinalizeChunkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func finalizeChunk<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_FinalizeChunkRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_FinalizeChunkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_FinalizeChunkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_FinalizeChunkResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_ChunkService.Method.FinalizeChunk.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_ChunkService.ClientProtocol {
    /// Call the "Get" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_GetChunkRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func get<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_GetChunkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetChunkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.get(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_GetChunkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_GetChunkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Put" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_PutChunkRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func put<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_PutChunkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PutChunkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.put(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_PutChunkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_PutChunkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PrepareChunk" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > External-signer single-chunk publish. Mirrors REST
    /// > `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
    /// > below the merkle threshold, so the payment shape is always wave-batch.
    /// > When the chunk is already on-network, the prepare response has
    /// > `already_stored = true` and the caller can skip the finalize step.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_PrepareChunkRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func prepareChunk<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_PrepareChunkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareChunkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.prepareChunk(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_PrepareChunkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_PrepareChunkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "FinalizeChunk" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_FinalizeChunkRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func finalizeChunk<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_FinalizeChunkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_FinalizeChunkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.finalizeChunk(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_FinalizeChunkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_FinalizeChunkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_ChunkService.ClientProtocol {
    /// Call the "Get" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func get<Result>(
        _ message: Antd_V1_GetChunkRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetChunkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_GetChunkRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.get(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Put" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func put<Result>(
        _ message: Antd_V1_PutChunkRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PutChunkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_PutChunkRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.put(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PrepareChunk" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > External-signer single-chunk publish. Mirrors REST
    /// > `/v1/chunks/prepare` + `/v1/chunks/finalize`. Single chunks are always
    /// > below the merkle threshold, so the payment shape is always wave-batch.
    /// > When the chunk is already on-network, the prepare response has
    /// > `already_stored = true` and the caller can skip the finalize step.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func prepareChunk<Result>(
        _ message: Antd_V1_PrepareChunkRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareChunkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_PrepareChunkRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.prepareChunk(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "FinalizeChunk" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func finalizeChunk<Result>(
        _ message: Antd_V1_FinalizeChunkRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_FinalizeChunkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_FinalizeChunkRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.finalizeChunk(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}