// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: antd/v1/files.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Antd_V1_PutFileRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// local filesystem path
  public var path: String = String()

  /// Optional payment mode: "auto" (default), "merkle", or "single". Empty
  /// string is treated as "auto" so old clients omitting the field stay
  /// wire-compatible.
  public var paymentMode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_PutFilePublicResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// hex — the DataMap's chunk address on the network
  public var address: String = String()

  /// Total storage cost paid in token units (atto). "0" if all chunks already existed.
  public var storageCostAtto: String = String()

  /// Total gas cost paid in wei, as a decimal string (u128 exceeds JSON safe-integer range).
  public var gasCostWei: String = String()

  /// Number of chunks stored on the network.
  public var chunksStored: UInt64 = 0

  /// Which payment mode was actually used ("auto", "merkle", or "single").
  public var paymentModeUsed: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_PutFileResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Hex-encoded rmp_serde-serialized DataMap. The caller keeps this; it is
  /// NOT stored on the network. Same shape as `PutDataResponse.data_map`.
  public var dataMap: String = String()

  /// Total storage cost paid in token units (atto). "0" if all chunks already existed.
  public var storageCostAtto: String = String()

  /// Total gas cost paid in wei, as a decimal string (u128 exceeds JSON safe-integer range).
  public var gasCostWei: String = String()

  /// Number of chunks stored on the network.
  public var chunksStored: UInt64 = 0

  /// Which payment mode was actually used ("auto", "merkle", or "single").
  public var paymentModeUsed: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_GetFilePublicRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// hex — DataMap chunk address
  public var address: String = String()

  /// local filesystem path
  public var destPath: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_GetFileRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// hex — rmp_serde-serialized DataMap
  public var dataMap: String = String()

  /// local filesystem path
  public var destPath: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Shared by GetPublic and Get — the file is written to dest_path, the response
/// itself is empty (success = file written, failure = RPC error).
public struct Antd_V1_GetFileResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_FileCostRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var path: String = String()

  public var isPublic: Bool = false

  /// Optional payment mode the estimate should reflect: "auto" (default),
  /// "merkle", or "single". Empty string is treated as "auto".
  public var paymentMode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "antd.v1"

extension Antd_V1_PutFileRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PutFileRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0\u{3}payment_mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.paymentMode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if !self.paymentMode.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentMode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_PutFileRequest, rhs: Antd_V1_PutFileRequest) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.paymentMode != rhs.paymentMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_PutFilePublicResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PutFilePublicResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}address\0\u{3}storage_cost_atto\0\u{3}gas_cost_wei\0\u{3}chunks_stored\0\u{3}payment_mode_used\0\u{b}cost\0\u{c}\u{1}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.address) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.storageCostAtto) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.gasCostWei) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.chunksStored) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.paymentModeUsed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 2)
    }
    if !self.storageCostAtto.isEmpty {
      try visitor.visitSingularStringField(value: self.storageCostAtto, fieldNumber: 3)
    }
    if !self.gasCostWei.isEmpty {
      try visitor.visitSingularStringField(value: self.gasCostWei, fieldNumber: 4)
    }
    if self.chunksStored != 0 {
      try visitor.visitSingularUInt64Field(value: self.chunksStored, fieldNumber: 5)
    }
    if !self.paymentModeUsed.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentModeUsed, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_PutFilePublicResponse, rhs: Antd_V1_PutFilePublicResponse) -> Bool {
    if lhs.address != rhs.address {return false}
    if lhs.storageCostAtto != rhs.storageCostAtto {return false}
    if lhs.gasCostWei != rhs.gasCostWei {return false}
    if lhs.chunksStored != rhs.chunksStored {return false}
    if lhs.paymentModeUsed != rhs.paymentModeUsed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_PutFileResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PutFileResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}data_map\0\u{3}storage_cost_atto\0\u{3}gas_cost_wei\0\u{3}chunks_stored\0\u{3}payment_mode_used\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.dataMap) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.storageCostAtto) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.gasCostWei) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.chunksStored) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.paymentModeUsed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.dataMap.isEmpty {
      try visitor.visitSingularStringField(value: self.dataMap, fieldNumber: 1)
    }
    if !self.storageCostAtto.isEmpty {
      try visitor.visitSingularStringField(value: self.storageCostAtto, fieldNumber: 2)
    }
    if !self.gasCostWei.isEmpty {
      try visitor.visitSingularStringField(value: self.gasCostWei, fieldNumber: 3)
    }
    if self.chunksStored != 0 {
      try visitor.visitSingularUInt64Field(value: self.chunksStored, fieldNumber: 4)
    }
    if !self.paymentModeUsed.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentModeUsed, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_PutFileResponse, rhs: Antd_V1_PutFileResponse) -> Bool {
    if lhs.dataMap != rhs.dataMap {return false}
    if lhs.storageCostAtto != rhs.storageCostAtto {return false}
    if lhs.gasCostWei != rhs.gasCostWei {return false}
    if lhs.chunksStored != rhs.chunksStored {return false}
    if lhs.paymentModeUsed != rhs.paymentModeUsed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_GetFilePublicRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetFilePublicRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}address\0\u{3}dest_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.address) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.destPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 1)
    }
    if !self.destPath.isEmpty {
      try visitor.visitSingularStringField(value: self.destPath, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_GetFilePublicRequest, rhs: Antd_V1_GetFilePublicRequest) -> Bool {
    if lhs.address != rhs.address {return false}
    if lhs.destPath != rhs.destPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_GetFileRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetFileRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}data_map\0\u{3}dest_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.dataMap) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.destPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.dataMap.isEmpty {
      try visitor.visitSingularStringField(value: self.dataMap, fieldNumber: 1)
    }
    if !self.destPath.isEmpty {
      try visitor.visitSingularStringField(value: self.destPath, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_GetFileRequest, rhs: Antd_V1_GetFileRequest) -> Bool {
    if lhs.dataMap != rhs.dataMap {return false}
    if lhs.destPath != rhs.destPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_GetFileResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetFileResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_GetFileResponse, rhs: Antd_V1_GetFileResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_FileCostRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileCostRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0\u{3}is_public\0\u{3}payment_mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isPublic) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.paymentMode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if self.isPublic != false {
      try visitor.visitSingularBoolField(value: self.isPublic, fieldNumber: 2)
    }
    if !self.paymentMode.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentMode, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_FileCostRequest, rhs: Antd_V1_FileCostRequest) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.isPublic != rhs.isPublic {return false}
    if lhs.paymentMode != rhs.paymentMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
