// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: antd/v1/health.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - antd.v1.HealthService

/// Namespace containing generated types for the "antd.v1.HealthService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Antd_V1_HealthService {
    /// Service descriptor for the "antd.v1.HealthService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.HealthService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Check" metadata.
        public enum Check {
            /// Request type for "Check".
            public typealias Input = Antd_V1_HealthCheckRequest
            /// Response type for "Check".
            public typealias Output = Antd_V1_HealthCheckResponse
            /// Descriptor for "Check".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.HealthService"),
                method: "Check"
            )
        }
        /// Descriptors for all methods in the "antd.v1.HealthService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Check.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "antd.v1.HealthService" service.
    public static let antd_v1_HealthService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.HealthService")
}

// MARK: antd.v1.HealthService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_HealthService {
    /// Streaming variant of the service protocol for the "antd.v1.HealthService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Check" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_HealthCheckRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_HealthCheckResponse` messages.
        func check(
            request: GRPCCore.StreamingServerRequest<Antd_V1_HealthCheckRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_HealthCheckResponse>
    }

    /// Service protocol for the "antd.v1.HealthService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Antd_V1_HealthService.StreamingServiceProtocol {
        /// Handle the "Check" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_HealthCheckRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_HealthCheckResponse` message.
        func check(
            request: GRPCCore.ServerRequest<Antd_V1_HealthCheckRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_HealthCheckResponse>
    }

    /// Simple service protocol for the "antd.v1.HealthService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Antd_V1_HealthService.ServiceProtocol {
        /// Handle the "Check" method.
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_HealthCheckRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_HealthCheckResponse` to respond with.
        func check(
            request: Antd_V1_HealthCheckRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_HealthCheckResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_HealthService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Antd_V1_HealthService.Method.Check.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_HealthCheckRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_HealthCheckResponse>(),
            handler: { request, context in
                try await self.check(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_HealthService.ServiceProtocol {
    public func check(
        request: GRPCCore.StreamingServerRequest<Antd_V1_HealthCheckRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_HealthCheckResponse> {
        let response = try await self.check(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_HealthService.SimpleServiceProtocol {
    public func check(
        request: GRPCCore.ServerRequest<Antd_V1_HealthCheckRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_HealthCheckResponse> {
        return GRPCCore.ServerResponse<Antd_V1_HealthCheckResponse>(
            message: try await self.check(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: antd.v1.HealthService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_HealthService {
    /// Generated client protocol for the "antd.v1.HealthService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Check" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_HealthCheckRequest` message.
        ///   - serializer: A serializer for `Antd_V1_HealthCheckRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_HealthCheckResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func check<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_HealthCheckRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_HealthCheckRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_HealthCheckResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_HealthCheckResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "antd.v1.HealthService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Check" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_HealthCheckRequest` message.
        ///   - serializer: A serializer for `Antd_V1_HealthCheckRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_HealthCheckResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func check<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_HealthCheckRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_HealthCheckRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_HealthCheckResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_HealthCheckResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_HealthService.Method.Check.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_HealthService.ClientProtocol {
    /// Call the "Check" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_HealthCheckRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func check<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_HealthCheckRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_HealthCheckResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.check(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_HealthCheckRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_HealthCheckResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_HealthService.ClientProtocol {
    /// Call the "Check" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func check<Result>(
        _ message: Antd_V1_HealthCheckRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_HealthCheckResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_HealthCheckRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.check(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}