// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: antd/v1/upload.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - antd.v1.UploadService

/// Namespace containing generated types for the "antd.v1.UploadService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Antd_V1_UploadService {
    /// Service descriptor for the "antd.v1.UploadService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.UploadService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "PrepareFileUpload" metadata.
        public enum PrepareFileUpload {
            /// Request type for "PrepareFileUpload".
            public typealias Input = Antd_V1_PrepareFileUploadRequest
            /// Response type for "PrepareFileUpload".
            public typealias Output = Antd_V1_PrepareUploadResponse
            /// Descriptor for "PrepareFileUpload".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.UploadService"),
                method: "PrepareFileUpload"
            )
        }
        /// Namespace for "PrepareDataUpload" metadata.
        public enum PrepareDataUpload {
            /// Request type for "PrepareDataUpload".
            public typealias Input = Antd_V1_PrepareDataUploadRequest
            /// Response type for "PrepareDataUpload".
            public typealias Output = Antd_V1_PrepareUploadResponse
            /// Descriptor for "PrepareDataUpload".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.UploadService"),
                method: "PrepareDataUpload"
            )
        }
        /// Namespace for "FinalizeUpload" metadata.
        public enum FinalizeUpload {
            /// Request type for "FinalizeUpload".
            public typealias Input = Antd_V1_FinalizeUploadRequest
            /// Response type for "FinalizeUpload".
            public typealias Output = Antd_V1_FinalizeUploadResponse
            /// Descriptor for "FinalizeUpload".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.UploadService"),
                method: "FinalizeUpload"
            )
        }
        /// Descriptors for all methods in the "antd.v1.UploadService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            PrepareFileUpload.descriptor,
            PrepareDataUpload.descriptor,
            FinalizeUpload.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "antd.v1.UploadService" service.
    public static let antd_v1_UploadService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.UploadService")
}

// MARK: antd.v1.UploadService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_UploadService {
    /// Streaming variant of the service protocol for the "antd.v1.UploadService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > External-signer flow for files + in-memory data. Mirrors the REST
    /// > `/v1/upload/prepare`, `/v1/data/prepare`, `/v1/upload/finalize` surface 1:1.
    /// > 
    /// > Two-phase: caller submits a prepare request, daemon collects quotes from the
    /// > network and stashes server-side state keyed by `upload_id`. Caller then
    /// > signs + submits the EVM payment off-daemon, then calls FinalizeUpload with
    /// > the resulting transaction artefacts.
    /// > 
    /// > Wave-batch (files with < 64 chunks): per-quote payments via `payForQuotes()`.
    /// > Merkle (files with >= 64 chunks): pool commitments via `payForMerkleTree2()`.
    /// > 
    /// > File and data prepares are intentionally separate RPCs (their request shapes
    /// > differ — filesystem path vs raw bytes), but they share one finalize RPC
    /// > because the server-side stored state is the same shape either way.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "PrepareFileUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1: prepare a file upload for external signing. Returns payment
        /// > details + an upload_id. For files with < 64 chunks returns
        /// > `payment_type = "wave_batch"`; otherwise `payment_type = "merkle"`.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_PrepareFileUploadRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_PrepareUploadResponse` messages.
        func prepareFileUpload(
            request: GRPCCore.StreamingServerRequest<Antd_V1_PrepareFileUploadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_PrepareUploadResponse>

        /// Handle the "PrepareDataUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1 (data): prepare an in-memory data upload for external signing.
        /// > Same as PrepareFileUpload but takes raw bytes instead of a filesystem
        /// > path. Honours visibility = "public" (requires ant-client #73, already
        /// > merged on main since 2026-05-05).
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_PrepareDataUploadRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_PrepareUploadResponse` messages.
        func prepareDataUpload(
            request: GRPCCore.StreamingServerRequest<Antd_V1_PrepareDataUploadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_PrepareUploadResponse>

        /// Handle the "FinalizeUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 2: finalize an upload after the external EVM payment has landed.
        /// > For wave-batch uploads pass `tx_hashes`; for merkle uploads pass
        /// > `winner_pool_hash` from the `MerklePaymentMade` event. The server-side
        /// > stored upload state is consumed (one-shot).
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_FinalizeUploadRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_FinalizeUploadResponse` messages.
        func finalizeUpload(
            request: GRPCCore.StreamingServerRequest<Antd_V1_FinalizeUploadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_FinalizeUploadResponse>
    }

    /// Service protocol for the "antd.v1.UploadService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > External-signer flow for files + in-memory data. Mirrors the REST
    /// > `/v1/upload/prepare`, `/v1/data/prepare`, `/v1/upload/finalize` surface 1:1.
    /// > 
    /// > Two-phase: caller submits a prepare request, daemon collects quotes from the
    /// > network and stashes server-side state keyed by `upload_id`. Caller then
    /// > signs + submits the EVM payment off-daemon, then calls FinalizeUpload with
    /// > the resulting transaction artefacts.
    /// > 
    /// > Wave-batch (files with < 64 chunks): per-quote payments via `payForQuotes()`.
    /// > Merkle (files with >= 64 chunks): pool commitments via `payForMerkleTree2()`.
    /// > 
    /// > File and data prepares are intentionally separate RPCs (their request shapes
    /// > differ — filesystem path vs raw bytes), but they share one finalize RPC
    /// > because the server-side stored state is the same shape either way.
    public protocol ServiceProtocol: Antd_V1_UploadService.StreamingServiceProtocol {
        /// Handle the "PrepareFileUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1: prepare a file upload for external signing. Returns payment
        /// > details + an upload_id. For files with < 64 chunks returns
        /// > `payment_type = "wave_batch"`; otherwise `payment_type = "merkle"`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareFileUploadRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_PrepareUploadResponse` message.
        func prepareFileUpload(
            request: GRPCCore.ServerRequest<Antd_V1_PrepareFileUploadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_PrepareUploadResponse>

        /// Handle the "PrepareDataUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1 (data): prepare an in-memory data upload for external signing.
        /// > Same as PrepareFileUpload but takes raw bytes instead of a filesystem
        /// > path. Honours visibility = "public" (requires ant-client #73, already
        /// > merged on main since 2026-05-05).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareDataUploadRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_PrepareUploadResponse` message.
        func prepareDataUpload(
            request: GRPCCore.ServerRequest<Antd_V1_PrepareDataUploadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_PrepareUploadResponse>

        /// Handle the "FinalizeUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 2: finalize an upload after the external EVM payment has landed.
        /// > For wave-batch uploads pass `tx_hashes`; for merkle uploads pass
        /// > `winner_pool_hash` from the `MerklePaymentMade` event. The server-side
        /// > stored upload state is consumed (one-shot).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_FinalizeUploadRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_FinalizeUploadResponse` message.
        func finalizeUpload(
            request: GRPCCore.ServerRequest<Antd_V1_FinalizeUploadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_FinalizeUploadResponse>
    }

    /// Simple service protocol for the "antd.v1.UploadService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > External-signer flow for files + in-memory data. Mirrors the REST
    /// > `/v1/upload/prepare`, `/v1/data/prepare`, `/v1/upload/finalize` surface 1:1.
    /// > 
    /// > Two-phase: caller submits a prepare request, daemon collects quotes from the
    /// > network and stashes server-side state keyed by `upload_id`. Caller then
    /// > signs + submits the EVM payment off-daemon, then calls FinalizeUpload with
    /// > the resulting transaction artefacts.
    /// > 
    /// > Wave-batch (files with < 64 chunks): per-quote payments via `payForQuotes()`.
    /// > Merkle (files with >= 64 chunks): pool commitments via `payForMerkleTree2()`.
    /// > 
    /// > File and data prepares are intentionally separate RPCs (their request shapes
    /// > differ — filesystem path vs raw bytes), but they share one finalize RPC
    /// > because the server-side stored state is the same shape either way.
    public protocol SimpleServiceProtocol: Antd_V1_UploadService.ServiceProtocol {
        /// Handle the "PrepareFileUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1: prepare a file upload for external signing. Returns payment
        /// > details + an upload_id. For files with < 64 chunks returns
        /// > `payment_type = "wave_batch"`; otherwise `payment_type = "merkle"`.
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_PrepareFileUploadRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_PrepareUploadResponse` to respond with.
        func prepareFileUpload(
            request: Antd_V1_PrepareFileUploadRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_PrepareUploadResponse

        /// Handle the "PrepareDataUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1 (data): prepare an in-memory data upload for external signing.
        /// > Same as PrepareFileUpload but takes raw bytes instead of a filesystem
        /// > path. Honours visibility = "public" (requires ant-client #73, already
        /// > merged on main since 2026-05-05).
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_PrepareDataUploadRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_PrepareUploadResponse` to respond with.
        func prepareDataUpload(
            request: Antd_V1_PrepareDataUploadRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_PrepareUploadResponse

        /// Handle the "FinalizeUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 2: finalize an upload after the external EVM payment has landed.
        /// > For wave-batch uploads pass `tx_hashes`; for merkle uploads pass
        /// > `winner_pool_hash` from the `MerklePaymentMade` event. The server-side
        /// > stored upload state is consumed (one-shot).
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_FinalizeUploadRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_FinalizeUploadResponse` to respond with.
        func finalizeUpload(
            request: Antd_V1_FinalizeUploadRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_FinalizeUploadResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_UploadService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Antd_V1_UploadService.Method.PrepareFileUpload.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_PrepareFileUploadRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_PrepareUploadResponse>(),
            handler: { request, context in
                try await self.prepareFileUpload(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Antd_V1_UploadService.Method.PrepareDataUpload.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_PrepareDataUploadRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_PrepareUploadResponse>(),
            handler: { request, context in
                try await self.prepareDataUpload(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Antd_V1_UploadService.Method.FinalizeUpload.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_FinalizeUploadRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_FinalizeUploadResponse>(),
            handler: { request, context in
                try await self.finalizeUpload(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_UploadService.ServiceProtocol {
    public func prepareFileUpload(
        request: GRPCCore.StreamingServerRequest<Antd_V1_PrepareFileUploadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_PrepareUploadResponse> {
        let response = try await self.prepareFileUpload(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func prepareDataUpload(
        request: GRPCCore.StreamingServerRequest<Antd_V1_PrepareDataUploadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_PrepareUploadResponse> {
        let response = try await self.prepareDataUpload(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func finalizeUpload(
        request: GRPCCore.StreamingServerRequest<Antd_V1_FinalizeUploadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_FinalizeUploadResponse> {
        let response = try await self.finalizeUpload(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_UploadService.SimpleServiceProtocol {
    public func prepareFileUpload(
        request: GRPCCore.ServerRequest<Antd_V1_PrepareFileUploadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_PrepareUploadResponse> {
        return GRPCCore.ServerResponse<Antd_V1_PrepareUploadResponse>(
            message: try await self.prepareFileUpload(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func prepareDataUpload(
        request: GRPCCore.ServerRequest<Antd_V1_PrepareDataUploadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_PrepareUploadResponse> {
        return GRPCCore.ServerResponse<Antd_V1_PrepareUploadResponse>(
            message: try await self.prepareDataUpload(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func finalizeUpload(
        request: GRPCCore.ServerRequest<Antd_V1_FinalizeUploadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_FinalizeUploadResponse> {
        return GRPCCore.ServerResponse<Antd_V1_FinalizeUploadResponse>(
            message: try await self.finalizeUpload(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: antd.v1.UploadService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_UploadService {
    /// Generated client protocol for the "antd.v1.UploadService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > External-signer flow for files + in-memory data. Mirrors the REST
    /// > `/v1/upload/prepare`, `/v1/data/prepare`, `/v1/upload/finalize` surface 1:1.
    /// > 
    /// > Two-phase: caller submits a prepare request, daemon collects quotes from the
    /// > network and stashes server-side state keyed by `upload_id`. Caller then
    /// > signs + submits the EVM payment off-daemon, then calls FinalizeUpload with
    /// > the resulting transaction artefacts.
    /// > 
    /// > Wave-batch (files with < 64 chunks): per-quote payments via `payForQuotes()`.
    /// > Merkle (files with >= 64 chunks): pool commitments via `payForMerkleTree2()`.
    /// > 
    /// > File and data prepares are intentionally separate RPCs (their request shapes
    /// > differ — filesystem path vs raw bytes), but they share one finalize RPC
    /// > because the server-side stored state is the same shape either way.
    public protocol ClientProtocol: Sendable {
        /// Call the "PrepareFileUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1: prepare a file upload for external signing. Returns payment
        /// > details + an upload_id. For files with < 64 chunks returns
        /// > `payment_type = "wave_batch"`; otherwise `payment_type = "merkle"`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareFileUploadRequest` message.
        ///   - serializer: A serializer for `Antd_V1_PrepareFileUploadRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_PrepareUploadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func prepareFileUpload<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_PrepareFileUploadRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_PrepareFileUploadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_PrepareUploadResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareUploadResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "PrepareDataUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1 (data): prepare an in-memory data upload for external signing.
        /// > Same as PrepareFileUpload but takes raw bytes instead of a filesystem
        /// > path. Honours visibility = "public" (requires ant-client #73, already
        /// > merged on main since 2026-05-05).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareDataUploadRequest` message.
        ///   - serializer: A serializer for `Antd_V1_PrepareDataUploadRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_PrepareUploadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func prepareDataUpload<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_PrepareDataUploadRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_PrepareDataUploadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_PrepareUploadResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareUploadResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "FinalizeUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 2: finalize an upload after the external EVM payment has landed.
        /// > For wave-batch uploads pass `tx_hashes`; for merkle uploads pass
        /// > `winner_pool_hash` from the `MerklePaymentMade` event. The server-side
        /// > stored upload state is consumed (one-shot).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_FinalizeUploadRequest` message.
        ///   - serializer: A serializer for `Antd_V1_FinalizeUploadRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_FinalizeUploadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func finalizeUpload<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_FinalizeUploadRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_FinalizeUploadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_FinalizeUploadResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_FinalizeUploadResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "antd.v1.UploadService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > External-signer flow for files + in-memory data. Mirrors the REST
    /// > `/v1/upload/prepare`, `/v1/data/prepare`, `/v1/upload/finalize` surface 1:1.
    /// > 
    /// > Two-phase: caller submits a prepare request, daemon collects quotes from the
    /// > network and stashes server-side state keyed by `upload_id`. Caller then
    /// > signs + submits the EVM payment off-daemon, then calls FinalizeUpload with
    /// > the resulting transaction artefacts.
    /// > 
    /// > Wave-batch (files with < 64 chunks): per-quote payments via `payForQuotes()`.
    /// > Merkle (files with >= 64 chunks): pool commitments via `payForMerkleTree2()`.
    /// > 
    /// > File and data prepares are intentionally separate RPCs (their request shapes
    /// > differ — filesystem path vs raw bytes), but they share one finalize RPC
    /// > because the server-side stored state is the same shape either way.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "PrepareFileUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1: prepare a file upload for external signing. Returns payment
        /// > details + an upload_id. For files with < 64 chunks returns
        /// > `payment_type = "wave_batch"`; otherwise `payment_type = "merkle"`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareFileUploadRequest` message.
        ///   - serializer: A serializer for `Antd_V1_PrepareFileUploadRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_PrepareUploadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func prepareFileUpload<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_PrepareFileUploadRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_PrepareFileUploadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_PrepareUploadResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareUploadResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_UploadService.Method.PrepareFileUpload.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "PrepareDataUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 1 (data): prepare an in-memory data upload for external signing.
        /// > Same as PrepareFileUpload but takes raw bytes instead of a filesystem
        /// > path. Honours visibility = "public" (requires ant-client #73, already
        /// > merged on main since 2026-05-05).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_PrepareDataUploadRequest` message.
        ///   - serializer: A serializer for `Antd_V1_PrepareDataUploadRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_PrepareUploadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func prepareDataUpload<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_PrepareDataUploadRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_PrepareDataUploadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_PrepareUploadResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareUploadResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_UploadService.Method.PrepareDataUpload.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "FinalizeUpload" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Phase 2: finalize an upload after the external EVM payment has landed.
        /// > For wave-batch uploads pass `tx_hashes`; for merkle uploads pass
        /// > `winner_pool_hash` from the `MerklePaymentMade` event. The server-side
        /// > stored upload state is consumed (one-shot).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_FinalizeUploadRequest` message.
        ///   - serializer: A serializer for `Antd_V1_FinalizeUploadRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_FinalizeUploadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func finalizeUpload<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_FinalizeUploadRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_FinalizeUploadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_FinalizeUploadResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_FinalizeUploadResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_UploadService.Method.FinalizeUpload.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_UploadService.ClientProtocol {
    /// Call the "PrepareFileUpload" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Phase 1: prepare a file upload for external signing. Returns payment
    /// > details + an upload_id. For files with < 64 chunks returns
    /// > `payment_type = "wave_batch"`; otherwise `payment_type = "merkle"`.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_PrepareFileUploadRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func prepareFileUpload<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_PrepareFileUploadRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareUploadResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.prepareFileUpload(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_PrepareFileUploadRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_PrepareUploadResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PrepareDataUpload" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Phase 1 (data): prepare an in-memory data upload for external signing.
    /// > Same as PrepareFileUpload but takes raw bytes instead of a filesystem
    /// > path. Honours visibility = "public" (requires ant-client #73, already
    /// > merged on main since 2026-05-05).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_PrepareDataUploadRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func prepareDataUpload<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_PrepareDataUploadRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareUploadResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.prepareDataUpload(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_PrepareDataUploadRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_PrepareUploadResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "FinalizeUpload" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Phase 2: finalize an upload after the external EVM payment has landed.
    /// > For wave-batch uploads pass `tx_hashes`; for merkle uploads pass
    /// > `winner_pool_hash` from the `MerklePaymentMade` event. The server-side
    /// > stored upload state is consumed (one-shot).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_FinalizeUploadRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func finalizeUpload<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_FinalizeUploadRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_FinalizeUploadResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.finalizeUpload(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_FinalizeUploadRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_FinalizeUploadResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_UploadService.ClientProtocol {
    /// Call the "PrepareFileUpload" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Phase 1: prepare a file upload for external signing. Returns payment
    /// > details + an upload_id. For files with < 64 chunks returns
    /// > `payment_type = "wave_batch"`; otherwise `payment_type = "merkle"`.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func prepareFileUpload<Result>(
        _ message: Antd_V1_PrepareFileUploadRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareUploadResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_PrepareFileUploadRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.prepareFileUpload(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PrepareDataUpload" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Phase 1 (data): prepare an in-memory data upload for external signing.
    /// > Same as PrepareFileUpload but takes raw bytes instead of a filesystem
    /// > path. Honours visibility = "public" (requires ant-client #73, already
    /// > merged on main since 2026-05-05).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func prepareDataUpload<Result>(
        _ message: Antd_V1_PrepareDataUploadRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_PrepareUploadResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_PrepareDataUploadRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.prepareDataUpload(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "FinalizeUpload" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Phase 2: finalize an upload after the external EVM payment has landed.
    /// > For wave-batch uploads pass `tx_hashes`; for merkle uploads pass
    /// > `winner_pool_hash` from the `MerklePaymentMade` event. The server-side
    /// > stored upload state is consumed (one-shot).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func finalizeUpload<Result>(
        _ message: Antd_V1_FinalizeUploadRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_FinalizeUploadResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_FinalizeUploadRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.finalizeUpload(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}