// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: antd/v1/upload.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Antd_V1_PrepareFileUploadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Local filesystem path on the daemon host.
  public var path: String = String()

  /// Upload visibility: "private" (default — DataMap returned to the caller)
  /// or "public" (DataMap chunk bundled into the same payment batch and
  /// stored on-network; its address is returned on finalize). Empty string
  /// is treated as "private".
  public var visibility: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_PrepareDataUploadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Raw bytes to upload.
  public var data: Data = Data()

  /// Same semantics as PrepareFileUploadRequest.visibility.
  public var visibility: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_PrepareUploadResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Opaque token to pass back to FinalizeUpload.
  public var uploadID: String = String()

  /// "wave_batch" or "merkle" — determines which fields are populated and
  /// which contract call the external signer must make.
  public var paymentType: String = String()

  /// --- Wave-batch fields (populated when payment_type == "wave_batch") ---
  /// Per-quote payment entries for `payForQuotes()`.
  public var payments: [Antd_V1_PaymentEntry] = []

  /// --- Merkle fields (populated when payment_type == "merkle") ---
  /// Merkle tree depth (1..=8).
  public var depth: UInt32 = 0

  /// Pool commitments for `payForMerkleTree2()`.
  public var poolCommitments: [Antd_V1_PoolCommitmentEntry] = []

  /// Timestamp for the merkle payment (unix seconds).
  public var merklePaymentTimestamp: UInt64 = 0

  /// --- Common fields (always populated) ---
  /// Total amount to pay in atto tokens as a decimal string. For merkle this
  /// is "0" since the cost is determined on-chain.
  public var totalAmount: String = String()

  /// Unified payment vault contract address (hex with 0x prefix).
  public var paymentVaultAddress: String = String()

  /// Payment token contract address (hex with 0x prefix).
  public var paymentTokenAddress: String = String()

  /// EVM RPC URL for submitting transactions.
  public var rpcURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A pool commitment entry for the merkle payment contract.
public struct Antd_V1_PoolCommitmentEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Pool hash (hex with 0x prefix, 32 bytes).
  public var poolHash: String = String()

  /// Exactly 16 candidate nodes.
  public var candidates: [Antd_V1_CandidateNodeEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A candidate node: rewards address + price (amount).
public struct Antd_V1_CandidateNodeEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Node's rewards address (hex with 0x prefix, 20 bytes).
  public var rewardsAddress: String = String()

  /// Node's price as a decimal string (maps to the contract's `amount` field).
  public var amount: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_FinalizeUploadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The upload_id returned from a Prepare* call.
  public var uploadID: String = String()

  /// Wave-batch: map of quote_hash (hex) → tx_hash (hex) from the on-chain
  /// payment. Required when the prepared upload was wave-batch, must be
  /// empty otherwise.
  public var txHashes: Dictionary<String,String> = [:]

  /// Merkle: winner pool hash (hex with 0x prefix, 32 bytes) from the
  /// `MerklePaymentMade` event. Required when the prepared upload was
  /// merkle, must be empty otherwise.
  public var winnerPoolHash: String = String()

  /// If true, store the DataMap on-network via the daemon's internal wallet
  /// and return its address. If false (default), return the raw DataMap
  /// for caller-side storage. Equivalent to the REST `store_data_map`
  /// field.
  public var storeDataMap: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_FinalizeUploadResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Hex-encoded rmp_serde-serialized DataMap. Always returned.
  public var dataMap: String = String()

  /// Network address of the stored DataMap, only set when the legacy
  /// `store_data_map = true` path published the DataMap via the daemon's
  /// internal wallet. New callers should prefer `visibility = "public"`
  /// on prepare and read `data_map_address` instead.
  public var address: String = String()

  /// Network address of the bundled DataMap chunk when the upload was
  /// prepared with `visibility = "public"`. The DataMap chunk's payment
  /// is part of the same external-signer batch as the data chunks, so
  /// no separate daemon-wallet payment is required.
  public var dataMapAddress: String = String()

  /// Number of chunks stored on the network.
  public var chunksStored: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "antd.v1"

extension Antd_V1_PrepareFileUploadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PrepareFileUploadRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0\u{1}visibility\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.visibility) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if !self.visibility.isEmpty {
      try visitor.visitSingularStringField(value: self.visibility, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_PrepareFileUploadRequest, rhs: Antd_V1_PrepareFileUploadRequest) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.visibility != rhs.visibility {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_PrepareDataUploadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PrepareDataUploadRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{1}visibility\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.visibility) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 1)
    }
    if !self.visibility.isEmpty {
      try visitor.visitSingularStringField(value: self.visibility, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_PrepareDataUploadRequest, rhs: Antd_V1_PrepareDataUploadRequest) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.visibility != rhs.visibility {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_PrepareUploadResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PrepareUploadResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}upload_id\0\u{3}payment_type\0\u{1}payments\0\u{1}depth\0\u{3}pool_commitments\0\u{3}merkle_payment_timestamp\0\u{3}total_amount\0\u{3}payment_vault_address\0\u{3}payment_token_address\0\u{3}rpc_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uploadID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.paymentType) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.payments) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.depth) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.poolCommitments) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.merklePaymentTimestamp) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.totalAmount) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.paymentVaultAddress) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.paymentTokenAddress) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.rpcURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.uploadID.isEmpty {
      try visitor.visitSingularStringField(value: self.uploadID, fieldNumber: 1)
    }
    if !self.paymentType.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentType, fieldNumber: 2)
    }
    if !self.payments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.payments, fieldNumber: 3)
    }
    if self.depth != 0 {
      try visitor.visitSingularUInt32Field(value: self.depth, fieldNumber: 4)
    }
    if !self.poolCommitments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.poolCommitments, fieldNumber: 5)
    }
    if self.merklePaymentTimestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.merklePaymentTimestamp, fieldNumber: 6)
    }
    if !self.totalAmount.isEmpty {
      try visitor.visitSingularStringField(value: self.totalAmount, fieldNumber: 7)
    }
    if !self.paymentVaultAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentVaultAddress, fieldNumber: 8)
    }
    if !self.paymentTokenAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentTokenAddress, fieldNumber: 9)
    }
    if !self.rpcURL.isEmpty {
      try visitor.visitSingularStringField(value: self.rpcURL, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_PrepareUploadResponse, rhs: Antd_V1_PrepareUploadResponse) -> Bool {
    if lhs.uploadID != rhs.uploadID {return false}
    if lhs.paymentType != rhs.paymentType {return false}
    if lhs.payments != rhs.payments {return false}
    if lhs.depth != rhs.depth {return false}
    if lhs.poolCommitments != rhs.poolCommitments {return false}
    if lhs.merklePaymentTimestamp != rhs.merklePaymentTimestamp {return false}
    if lhs.totalAmount != rhs.totalAmount {return false}
    if lhs.paymentVaultAddress != rhs.paymentVaultAddress {return false}
    if lhs.paymentTokenAddress != rhs.paymentTokenAddress {return false}
    if lhs.rpcURL != rhs.rpcURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_PoolCommitmentEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PoolCommitmentEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}pool_hash\0\u{1}candidates\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.poolHash) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.candidates) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.poolHash.isEmpty {
      try visitor.visitSingularStringField(value: self.poolHash, fieldNumber: 1)
    }
    if !self.candidates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.candidates, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_PoolCommitmentEntry, rhs: Antd_V1_PoolCommitmentEntry) -> Bool {
    if lhs.poolHash != rhs.poolHash {return false}
    if lhs.candidates != rhs.candidates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_CandidateNodeEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CandidateNodeEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}rewards_address\0\u{1}amount\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.rewardsAddress) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.amount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.rewardsAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.rewardsAddress, fieldNumber: 1)
    }
    if !self.amount.isEmpty {
      try visitor.visitSingularStringField(value: self.amount, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_CandidateNodeEntry, rhs: Antd_V1_CandidateNodeEntry) -> Bool {
    if lhs.rewardsAddress != rhs.rewardsAddress {return false}
    if lhs.amount != rhs.amount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_FinalizeUploadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FinalizeUploadRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}upload_id\0\u{3}tx_hashes\0\u{3}winner_pool_hash\0\u{3}store_data_map\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uploadID) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.txHashes) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.winnerPoolHash) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.storeDataMap) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.uploadID.isEmpty {
      try visitor.visitSingularStringField(value: self.uploadID, fieldNumber: 1)
    }
    if !self.txHashes.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.txHashes, fieldNumber: 2)
    }
    if !self.winnerPoolHash.isEmpty {
      try visitor.visitSingularStringField(value: self.winnerPoolHash, fieldNumber: 3)
    }
    if self.storeDataMap != false {
      try visitor.visitSingularBoolField(value: self.storeDataMap, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_FinalizeUploadRequest, rhs: Antd_V1_FinalizeUploadRequest) -> Bool {
    if lhs.uploadID != rhs.uploadID {return false}
    if lhs.txHashes != rhs.txHashes {return false}
    if lhs.winnerPoolHash != rhs.winnerPoolHash {return false}
    if lhs.storeDataMap != rhs.storeDataMap {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_FinalizeUploadResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FinalizeUploadResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}data_map\0\u{1}address\0\u{3}data_map_address\0\u{3}chunks_stored\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.dataMap) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.address) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.dataMapAddress) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.chunksStored) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.dataMap.isEmpty {
      try visitor.visitSingularStringField(value: self.dataMap, fieldNumber: 1)
    }
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 2)
    }
    if !self.dataMapAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.dataMapAddress, fieldNumber: 3)
    }
    if self.chunksStored != 0 {
      try visitor.visitSingularUInt64Field(value: self.chunksStored, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_FinalizeUploadResponse, rhs: Antd_V1_FinalizeUploadResponse) -> Bool {
    if lhs.dataMap != rhs.dataMap {return false}
    if lhs.address != rhs.address {return false}
    if lhs.dataMapAddress != rhs.dataMapAddress {return false}
    if lhs.chunksStored != rhs.chunksStored {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
