// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: antd/v1/wallet.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - antd.v1.WalletService

/// Namespace containing generated types for the "antd.v1.WalletService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Antd_V1_WalletService {
    /// Service descriptor for the "antd.v1.WalletService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.WalletService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "GetAddress" metadata.
        public enum GetAddress {
            /// Request type for "GetAddress".
            public typealias Input = Antd_V1_GetWalletAddressRequest
            /// Response type for "GetAddress".
            public typealias Output = Antd_V1_GetWalletAddressResponse
            /// Descriptor for "GetAddress".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.WalletService"),
                method: "GetAddress"
            )
        }
        /// Namespace for "GetBalance" metadata.
        public enum GetBalance {
            /// Request type for "GetBalance".
            public typealias Input = Antd_V1_GetWalletBalanceRequest
            /// Response type for "GetBalance".
            public typealias Output = Antd_V1_GetWalletBalanceResponse
            /// Descriptor for "GetBalance".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.WalletService"),
                method: "GetBalance"
            )
        }
        /// Namespace for "Approve" metadata.
        public enum Approve {
            /// Request type for "Approve".
            public typealias Input = Antd_V1_WalletApproveRequest
            /// Response type for "Approve".
            public typealias Output = Antd_V1_WalletApproveResponse
            /// Descriptor for "Approve".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.WalletService"),
                method: "Approve"
            )
        }
        /// Descriptors for all methods in the "antd.v1.WalletService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetAddress.descriptor,
            GetBalance.descriptor,
            Approve.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "antd.v1.WalletService" service.
    public static let antd_v1_WalletService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "antd.v1.WalletService")
}

// MARK: antd.v1.WalletService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_WalletService {
    /// Streaming variant of the service protocol for the "antd.v1.WalletService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.
    /// > 
    /// > All three RPCs require the daemon to have been started with a configured
    /// > wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
    /// > daemon returns `Status::failed_precondition` with the same "wallet not
    /// > configured" message the REST handlers return as 503.
    /// > 
    /// > External-signer flows do NOT use this service — they pay via off-daemon
    /// > EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
    /// > `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
    /// > for callers that have entrusted a key to the daemon.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetAddress" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's on-chain address (hex with 0x prefix).
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_GetWalletAddressRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_GetWalletAddressResponse` messages.
        func getAddress(
            request: GRPCCore.StreamingServerRequest<Antd_V1_GetWalletAddressRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_GetWalletAddressResponse>

        /// Handle the "GetBalance" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's token + gas balances.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_GetWalletBalanceRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_GetWalletBalanceResponse` messages.
        func getBalance(
            request: GRPCCore.StreamingServerRequest<Antd_V1_GetWalletBalanceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_GetWalletBalanceResponse>

        /// Handle the "Approve" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Approves the wallet to spend tokens on the payment vault contract.
        /// > One-time operation; safe to call repeatedly (idempotent at the contract
        /// > level — a no-op once approval is in place).
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Antd_V1_WalletApproveRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Antd_V1_WalletApproveResponse` messages.
        func approve(
            request: GRPCCore.StreamingServerRequest<Antd_V1_WalletApproveRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_WalletApproveResponse>
    }

    /// Service protocol for the "antd.v1.WalletService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.
    /// > 
    /// > All three RPCs require the daemon to have been started with a configured
    /// > wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
    /// > daemon returns `Status::failed_precondition` with the same "wallet not
    /// > configured" message the REST handlers return as 503.
    /// > 
    /// > External-signer flows do NOT use this service — they pay via off-daemon
    /// > EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
    /// > `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
    /// > for callers that have entrusted a key to the daemon.
    public protocol ServiceProtocol: Antd_V1_WalletService.StreamingServiceProtocol {
        /// Handle the "GetAddress" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's on-chain address (hex with 0x prefix).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetWalletAddressRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_GetWalletAddressResponse` message.
        func getAddress(
            request: GRPCCore.ServerRequest<Antd_V1_GetWalletAddressRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_GetWalletAddressResponse>

        /// Handle the "GetBalance" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's token + gas balances.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetWalletBalanceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_GetWalletBalanceResponse` message.
        func getBalance(
            request: GRPCCore.ServerRequest<Antd_V1_GetWalletBalanceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_GetWalletBalanceResponse>

        /// Handle the "Approve" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Approves the wallet to spend tokens on the payment vault contract.
        /// > One-time operation; safe to call repeatedly (idempotent at the contract
        /// > level — a no-op once approval is in place).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_WalletApproveRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Antd_V1_WalletApproveResponse` message.
        func approve(
            request: GRPCCore.ServerRequest<Antd_V1_WalletApproveRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Antd_V1_WalletApproveResponse>
    }

    /// Simple service protocol for the "antd.v1.WalletService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.
    /// > 
    /// > All three RPCs require the daemon to have been started with a configured
    /// > wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
    /// > daemon returns `Status::failed_precondition` with the same "wallet not
    /// > configured" message the REST handlers return as 503.
    /// > 
    /// > External-signer flows do NOT use this service — they pay via off-daemon
    /// > EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
    /// > `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
    /// > for callers that have entrusted a key to the daemon.
    public protocol SimpleServiceProtocol: Antd_V1_WalletService.ServiceProtocol {
        /// Handle the "GetAddress" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's on-chain address (hex with 0x prefix).
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_GetWalletAddressRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_GetWalletAddressResponse` to respond with.
        func getAddress(
            request: Antd_V1_GetWalletAddressRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_GetWalletAddressResponse

        /// Handle the "GetBalance" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's token + gas balances.
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_GetWalletBalanceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_GetWalletBalanceResponse` to respond with.
        func getBalance(
            request: Antd_V1_GetWalletBalanceRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_GetWalletBalanceResponse

        /// Handle the "Approve" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Approves the wallet to spend tokens on the payment vault contract.
        /// > One-time operation; safe to call repeatedly (idempotent at the contract
        /// > level — a no-op once approval is in place).
        ///
        /// - Parameters:
        ///   - request: A `Antd_V1_WalletApproveRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Antd_V1_WalletApproveResponse` to respond with.
        func approve(
            request: Antd_V1_WalletApproveRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Antd_V1_WalletApproveResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_WalletService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Antd_V1_WalletService.Method.GetAddress.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_GetWalletAddressRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_GetWalletAddressResponse>(),
            handler: { request, context in
                try await self.getAddress(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Antd_V1_WalletService.Method.GetBalance.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_GetWalletBalanceRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_GetWalletBalanceResponse>(),
            handler: { request, context in
                try await self.getBalance(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Antd_V1_WalletService.Method.Approve.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_WalletApproveRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_WalletApproveResponse>(),
            handler: { request, context in
                try await self.approve(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_WalletService.ServiceProtocol {
    public func getAddress(
        request: GRPCCore.StreamingServerRequest<Antd_V1_GetWalletAddressRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_GetWalletAddressResponse> {
        let response = try await self.getAddress(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func getBalance(
        request: GRPCCore.StreamingServerRequest<Antd_V1_GetWalletBalanceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_GetWalletBalanceResponse> {
        let response = try await self.getBalance(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func approve(
        request: GRPCCore.StreamingServerRequest<Antd_V1_WalletApproveRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Antd_V1_WalletApproveResponse> {
        let response = try await self.approve(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_WalletService.SimpleServiceProtocol {
    public func getAddress(
        request: GRPCCore.ServerRequest<Antd_V1_GetWalletAddressRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_GetWalletAddressResponse> {
        return GRPCCore.ServerResponse<Antd_V1_GetWalletAddressResponse>(
            message: try await self.getAddress(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func getBalance(
        request: GRPCCore.ServerRequest<Antd_V1_GetWalletBalanceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_GetWalletBalanceResponse> {
        return GRPCCore.ServerResponse<Antd_V1_GetWalletBalanceResponse>(
            message: try await self.getBalance(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func approve(
        request: GRPCCore.ServerRequest<Antd_V1_WalletApproveRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Antd_V1_WalletApproveResponse> {
        return GRPCCore.ServerResponse<Antd_V1_WalletApproveResponse>(
            message: try await self.approve(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: antd.v1.WalletService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_WalletService {
    /// Generated client protocol for the "antd.v1.WalletService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.
    /// > 
    /// > All three RPCs require the daemon to have been started with a configured
    /// > wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
    /// > daemon returns `Status::failed_precondition` with the same "wallet not
    /// > configured" message the REST handlers return as 503.
    /// > 
    /// > External-signer flows do NOT use this service — they pay via off-daemon
    /// > EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
    /// > `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
    /// > for callers that have entrusted a key to the daemon.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetAddress" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's on-chain address (hex with 0x prefix).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetWalletAddressRequest` message.
        ///   - serializer: A serializer for `Antd_V1_GetWalletAddressRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_GetWalletAddressResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getAddress<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_GetWalletAddressRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_GetWalletAddressRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_GetWalletAddressResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetWalletAddressResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetBalance" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's token + gas balances.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetWalletBalanceRequest` message.
        ///   - serializer: A serializer for `Antd_V1_GetWalletBalanceRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_GetWalletBalanceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getBalance<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_GetWalletBalanceRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_GetWalletBalanceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_GetWalletBalanceResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetWalletBalanceResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Approve" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Approves the wallet to spend tokens on the payment vault contract.
        /// > One-time operation; safe to call repeatedly (idempotent at the contract
        /// > level — a no-op once approval is in place).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_WalletApproveRequest` message.
        ///   - serializer: A serializer for `Antd_V1_WalletApproveRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_WalletApproveResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func approve<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_WalletApproveRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_WalletApproveRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_WalletApproveResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_WalletApproveResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "antd.v1.WalletService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.
    /// > 
    /// > All three RPCs require the daemon to have been started with a configured
    /// > wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
    /// > daemon returns `Status::failed_precondition` with the same "wallet not
    /// > configured" message the REST handlers return as 503.
    /// > 
    /// > External-signer flows do NOT use this service — they pay via off-daemon
    /// > EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
    /// > `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
    /// > for callers that have entrusted a key to the daemon.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetAddress" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's on-chain address (hex with 0x prefix).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetWalletAddressRequest` message.
        ///   - serializer: A serializer for `Antd_V1_GetWalletAddressRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_GetWalletAddressResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getAddress<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_GetWalletAddressRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_GetWalletAddressRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_GetWalletAddressResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetWalletAddressResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_WalletService.Method.GetAddress.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetBalance" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns the wallet's token + gas balances.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_GetWalletBalanceRequest` message.
        ///   - serializer: A serializer for `Antd_V1_GetWalletBalanceRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_GetWalletBalanceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getBalance<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_GetWalletBalanceRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_GetWalletBalanceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_GetWalletBalanceResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetWalletBalanceResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_WalletService.Method.GetBalance.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Approve" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Approves the wallet to spend tokens on the payment vault contract.
        /// > One-time operation; safe to call repeatedly (idempotent at the contract
        /// > level — a no-op once approval is in place).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Antd_V1_WalletApproveRequest` message.
        ///   - serializer: A serializer for `Antd_V1_WalletApproveRequest` messages.
        ///   - deserializer: A deserializer for `Antd_V1_WalletApproveResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func approve<Result>(
            request: GRPCCore.ClientRequest<Antd_V1_WalletApproveRequest>,
            serializer: some GRPCCore.MessageSerializer<Antd_V1_WalletApproveRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Antd_V1_WalletApproveResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_WalletApproveResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Antd_V1_WalletService.Method.Approve.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_WalletService.ClientProtocol {
    /// Call the "GetAddress" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Returns the wallet's on-chain address (hex with 0x prefix).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_GetWalletAddressRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getAddress<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_GetWalletAddressRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetWalletAddressResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getAddress(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_GetWalletAddressRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_GetWalletAddressResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetBalance" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Returns the wallet's token + gas balances.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_GetWalletBalanceRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBalance<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_GetWalletBalanceRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetWalletBalanceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getBalance(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_GetWalletBalanceRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_GetWalletBalanceResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Approve" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Approves the wallet to spend tokens on the payment vault contract.
    /// > One-time operation; safe to call repeatedly (idempotent at the contract
    /// > level — a no-op once approval is in place).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Antd_V1_WalletApproveRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func approve<Result>(
        request: GRPCCore.ClientRequest<Antd_V1_WalletApproveRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_WalletApproveResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.approve(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Antd_V1_WalletApproveRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Antd_V1_WalletApproveResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Antd_V1_WalletService.ClientProtocol {
    /// Call the "GetAddress" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Returns the wallet's on-chain address (hex with 0x prefix).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getAddress<Result>(
        _ message: Antd_V1_GetWalletAddressRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetWalletAddressResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_GetWalletAddressRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getAddress(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetBalance" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Returns the wallet's token + gas balances.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBalance<Result>(
        _ message: Antd_V1_GetWalletBalanceRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_GetWalletBalanceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_GetWalletBalanceRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getBalance(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Approve" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Approves the wallet to spend tokens on the payment vault contract.
    /// > One-time operation; safe to call repeatedly (idempotent at the contract
    /// > level — a no-op once approval is in place).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func approve<Result>(
        _ message: Antd_V1_WalletApproveRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Antd_V1_WalletApproveResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Antd_V1_WalletApproveRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.approve(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}