# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: antd/v1/data.proto for package 'antd.v1'

require 'grpc'
require 'antd/v1/data_pb'

module Antd
  module V1
    module DataService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'antd.v1.DataService'

        # Private = unqualified verb (the DataMap is returned to the caller; it is
        # NOT stored on the network). Public = `_public` suffix (the DataMap is
        # additionally stored on-network and the call returns the resulting address).
        rpc :Put, ::Antd::V1::PutDataRequest, ::Antd::V1::PutDataResponse
        rpc :PutPublic, ::Antd::V1::PutPublicDataRequest, ::Antd::V1::PutPublicDataResponse
        rpc :Get, ::Antd::V1::GetDataRequest, ::Antd::V1::GetDataResponse
        rpc :GetPublic, ::Antd::V1::GetPublicDataRequest, ::Antd::V1::GetPublicDataResponse
        # Streaming downloads — constant memory, one decrypt batch at a time.
        # Private streams from a caller-held DataMap; public resolves the address
        # to a DataMap first (Stream is the primitive, StreamPublic wraps it).
        rpc :Stream, ::Antd::V1::StreamDataRequest, stream(::Antd::V1::DataChunk)
        rpc :StreamPublic, ::Antd::V1::StreamPublicDataRequest, stream(::Antd::V1::DataChunk)
        rpc :Cost, ::Antd::V1::DataCostRequest, ::Antd::V1::Cost
      end

      Stub = Service.rpc_stub_class
    end
  end
end
