# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: antd/v1/files.proto for package 'antd.v1'

require 'grpc'
require 'antd/v1/files_pb'

module Antd
  module V1
    module FileService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'antd.v1.FileService'

        # Private = unqualified verb (the DataMap is returned to the caller; it is
        # NOT stored on the network). Public = `_public` suffix (the DataMap is
        # additionally stored on-network and the call returns the resulting address).
        rpc :Put, ::Antd::V1::PutFileRequest, ::Antd::V1::PutFileResponse
        rpc :PutPublic, ::Antd::V1::PutFileRequest, ::Antd::V1::PutFilePublicResponse
        rpc :Get, ::Antd::V1::GetFileRequest, ::Antd::V1::GetFileResponse
        rpc :GetPublic, ::Antd::V1::GetFilePublicRequest, ::Antd::V1::GetFileResponse
        rpc :Cost, ::Antd::V1::FileCostRequest, ::Antd::V1::Cost
      end

      Stub = Service.rpc_stub_class
    end
  end
end
