# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antd/v1/files.proto

require 'google/protobuf'

require 'antd/v1/common_pb'


descriptor_data = "\n\x13\x61ntd/v1/files.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"4\n\x0ePutFileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x14\n\x0cpayment_mode\x18\x02 \x01(\t\"\x97\x01\n\x15PutFilePublicResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x19\n\x11storage_cost_atto\x18\x03 \x01(\t\x12\x14\n\x0cgas_cost_wei\x18\x04 \x01(\t\x12\x15\n\rchunks_stored\x18\x05 \x01(\x04\x12\x19\n\x11payment_mode_used\x18\x06 \x01(\tJ\x04\x08\x01\x10\x02R\x04\x63ost\"\x86\x01\n\x0fPutFileResponse\x12\x10\n\x08\x64\x61ta_map\x18\x01 \x01(\t\x12\x19\n\x11storage_cost_atto\x18\x02 \x01(\t\x12\x14\n\x0cgas_cost_wei\x18\x03 \x01(\t\x12\x15\n\rchunks_stored\x18\x04 \x01(\x04\x12\x19\n\x11payment_mode_used\x18\x05 \x01(\t\":\n\x14GetFilePublicRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x11\n\tdest_path\x18\x02 \x01(\t\"5\n\x0eGetFileRequest\x12\x10\n\x08\x64\x61ta_map\x18\x01 \x01(\t\x12\x11\n\tdest_path\x18\x02 \x01(\t\"\x11\n\x0fGetFileResponse\"H\n\x0f\x46ileCostRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\tis_public\x18\x02 \x01(\x08\x12\x14\n\x0cpayment_mode\x18\x03 \x01(\t2\xbe\x02\n\x0b\x46ileService\x12\x38\n\x03Put\x12\x17.antd.v1.PutFileRequest\x1a\x18.antd.v1.PutFileResponse\x12\x44\n\tPutPublic\x12\x17.antd.v1.PutFileRequest\x1a\x1e.antd.v1.PutFilePublicResponse\x12\x38\n\x03Get\x12\x17.antd.v1.GetFileRequest\x1a\x18.antd.v1.GetFileResponse\x12\x44\n\tGetPublic\x12\x1d.antd.v1.GetFilePublicRequest\x1a\x18.antd.v1.GetFileResponse\x12/\n\x04\x43ost\x12\x18.antd.v1.FileCostRequest\x1a\r.antd.v1.CostBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\x07\x41ntd.V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Antd
  module V1
    PutFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutFileRequest").msgclass
    PutFilePublicResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutFilePublicResponse").msgclass
    PutFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutFileResponse").msgclass
    GetFilePublicRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetFilePublicRequest").msgclass
    GetFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetFileRequest").msgclass
    GetFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetFileResponse").msgclass
    FileCostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.FileCostRequest").msgclass
  end
end
