# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: antd/v1/health.proto for package 'antd.v1'

require 'grpc'
require 'antd/v1/health_pb'

module Antd
  module V1
    module HealthService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'antd.v1.HealthService'

        rpc :Check, ::Antd::V1::HealthCheckRequest, ::Antd::V1::HealthCheckResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
