# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: antd/v1/wallet.proto for package 'antd.v1'

require 'grpc'
require 'antd/v1/wallet_pb'

module Antd
  module V1
    module WalletService
      # Wallet operations. Mirrors the REST `/v1/wallet/*` surface 1:1.
      #
      # All three RPCs require the daemon to have been started with a configured
      # wallet (the `AUTONOMI_WALLET_KEY` env var). When the wallet is absent the
      # daemon returns `Status::failed_precondition` with the same "wallet not
      # configured" message the REST handlers return as 503.
      #
      # External-signer flows do NOT use this service — they pay via off-daemon
      # EVM transactions, see `UploadService` and `ChunkService.PrepareChunk` /
      # `FinalizeChunk` for the prepare/finalize surface. `WalletService` is only
      # for callers that have entrusted a key to the daemon.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'antd.v1.WalletService'

        # Returns the wallet's on-chain address (hex with 0x prefix).
        rpc :GetAddress, ::Antd::V1::GetWalletAddressRequest, ::Antd::V1::GetWalletAddressResponse
        # Returns the wallet's token + gas balances.
        rpc :GetBalance, ::Antd::V1::GetWalletBalanceRequest, ::Antd::V1::GetWalletBalanceResponse
        # Approves the wallet to spend tokens on the payment vault contract.
        # One-time operation; safe to call repeatedly (idempotent at the contract
        # level — a no-op once approval is in place).
        rpc :Approve, ::Antd::V1::WalletApproveRequest, ::Antd::V1::WalletApproveResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
