# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antd/v1/wallet.proto

require 'google/protobuf'


descriptor_data = "\n\x14\x61ntd/v1/wallet.proto\x12\x07\x61ntd.v1\"\x19\n\x17GetWalletAddressRequest\"+\n\x18GetWalletAddressResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x19\n\x17GetWalletBalanceRequest\"@\n\x18GetWalletBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\t\x12\x13\n\x0bgas_balance\x18\x02 \x01(\t\"\x16\n\x14WalletApproveRequest\")\n\x15WalletApproveResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x32\xff\x01\n\rWalletService\x12Q\n\nGetAddress\x12 .antd.v1.GetWalletAddressRequest\x1a!.antd.v1.GetWalletAddressResponse\x12Q\n\nGetBalance\x12 .antd.v1.GetWalletBalanceRequest\x1a!.antd.v1.GetWalletBalanceResponse\x12H\n\x07\x41pprove\x12\x1d.antd.v1.WalletApproveRequest\x1a\x1e.antd.v1.WalletApproveResponseBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\x07\x41ntd.V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Antd
  module V1
    GetWalletAddressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetWalletAddressRequest").msgclass
    GetWalletAddressResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetWalletAddressResponse").msgclass
    GetWalletBalanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetWalletBalanceRequest").msgclass
    GetWalletBalanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetWalletBalanceResponse").msgclass
    WalletApproveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.WalletApproveRequest").msgclass
    WalletApproveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.WalletApproveResponse").msgclass
  end
end
